// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Password Exchange Support",
            "url": "https://github.com/Anthony-Bible/password-exchange"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/health": {
            "get": {
                "description": "Returns the health status of the API and its dependencies",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Utility"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "Service health status",
                        "schema": {
                            "$ref": "#/definitions/models.HealthCheckResponse"
                        }
                    }
                }
            }
        },
        "/info": {
            "get": {
                "description": "Returns information about the API including available endpoints and features",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Utility"
                ],
                "summary": "API information",
                "responses": {
                    "200": {
                        "description": "API information",
                        "schema": {
                            "$ref": "#/definitions/models.APIInfoResponse"
                        }
                    }
                }
            }
        },
        "/messages": {
            "post": {
                "description": "Creates a new encrypted message that can be accessed via a unique URL. Optionally sends email notifications to the recipient.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Messages"
                ],
                "summary": "Submit a new message",
                "parameters": [
                    {
                        "description": "Message submission request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.MessageSubmissionRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Message successfully created",
                        "schema": {
                            "$ref": "#/definitions/models.MessageSubmissionResponse"
                        }
                    },
                    "400": {
                        "description": "Validation error",
                        "schema": {
                            "$ref": "#/definitions/models.StandardErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Anti-spam verification failed",
                        "schema": {
                            "$ref": "#/definitions/models.StandardErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/models.StandardErrorResponse"
                        }
                    }
                }
            }
        },
        "/messages/{id}": {
            "get": {
                "description": "Retrieves information about a message including whether it exists, requires a passphrase, and has been accessed.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Messages"
                ],
                "summary": "Get message access information",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "Message ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "format": "byte",
                        "description": "Base64-encoded decryption key",
                        "name": "key",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Message information retrieved",
                        "schema": {
                            "$ref": "#/definitions/models.MessageAccessInfoResponse"
                        }
                    },
                    "404": {
                        "description": "Message not found or expired",
                        "schema": {
                            "$ref": "#/definitions/models.StandardErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/models.StandardErrorResponse"
                        }
                    }
                }
            }
        },
        "/messages/{id}/decrypt": {
            "post": {
                "description": "Decrypts and retrieves the message content. This is a one-time operation that will delete the message after successful decryption.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Messages"
                ],
                "summary": "Decrypt a message",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "Message ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Decryption request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.MessageDecryptRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Message successfully decrypted",
                        "schema": {
                            "$ref": "#/definitions/models.MessageDecryptResponse"
                        }
                    },
                    "401": {
                        "description": "Invalid passphrase",
                        "schema": {
                            "$ref": "#/definitions/models.StandardErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Message not found or expired",
                        "schema": {
                            "$ref": "#/definitions/models.StandardErrorResponse"
                        }
                    },
                    "410": {
                        "description": "Message already consumed",
                        "schema": {
                            "$ref": "#/definitions/models.StandardErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/models.StandardErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.APIInfoResponse": {
            "type": "object",
            "properties": {
                "documentation": {
                    "description": "URL to the API documentation",
                    "type": "string",
                    "example": "/api/v1/docs"
                },
                "endpoints": {
                    "description": "Map of available API endpoints",
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    },
                    "example": {
                        "submit": "POST /api/v1/messages"
                    }
                },
                "features": {
                    "description": "Map of enabled features",
                    "type": "object",
                    "additionalProperties": {
                        "type": "boolean"
                    },
                    "example": {
                        "emailNotifications": true
                    }
                },
                "version": {
                    "description": "API version",
                    "type": "string",
                    "example": "1.0.0"
                }
            }
        },
        "models.HealthCheckResponse": {
            "type": "object",
            "properties": {
                "services": {
                    "description": "Detailed status of individual components",
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    },
                    "example": {
                        "database": "healthy",
                        "encryption": "healthy"
                    }
                },
                "status": {
                    "description": "Overall status of the service",
                    "type": "string",
                    "example": "healthy"
                },
                "timestamp": {
                    "description": "Timestamp of the health check",
                    "type": "string"
                },
                "version": {
                    "description": "Service version",
                    "type": "string",
                    "example": "1.0.0"
                }
            }
        },
        "models.MessageAccessInfoResponse": {
            "type": "object",
            "properties": {
                "exists": {
                    "description": "Whether the message exists and is still available",
                    "type": "boolean",
                    "example": true
                },
                "expiresAt": {
                    "description": "When the message will expire",
                    "type": "string"
                },
                "hasBeenAccessed": {
                    "description": "Whether the message has already been accessed",
                    "type": "boolean",
                    "example": false
                },
                "messageId": {
                    "description": "Unique identifier for the message",
                    "type": "string",
                    "example": "123e4567-e89b-12d3-a456-426614174000"
                },
                "requiresPassphrase": {
                    "description": "Whether a passphrase is required to decrypt the message",
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "models.MessageDecryptRequest": {
            "type": "object",
            "required": [
                "decryptionKey"
            ],
            "properties": {
                "decryptionKey": {
                    "description": "Base64 encoded encryption key",
                    "type": "string",
                    "example": "YWJjZGVmZ2hpams="
                },
                "passphrase": {
                    "description": "Optional passphrase (required if message is passphrase protected)",
                    "type": "string",
                    "example": "correct-horse-battery-staple"
                }
            }
        },
        "models.MessageDecryptResponse": {
            "type": "object",
            "properties": {
                "content": {
                    "description": "Decrypted content of the message",
                    "type": "string",
                    "example": "This was a secret message"
                },
                "decryptedAt": {
                    "description": "When the message was decrypted",
                    "type": "string"
                },
                "expiresAt": {
                    "description": "When the message will expire",
                    "type": "string"
                },
                "maxViewCount": {
                    "description": "Maximum allowed views for this message",
                    "type": "integer",
                    "example": 5
                },
                "messageId": {
                    "description": "Unique identifier for the message",
                    "type": "string",
                    "example": "123e4567-e89b-12d3-a456-426614174000"
                },
                "viewCount": {
                    "description": "Current number of times the message has been viewed",
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "models.MessageSubmissionRequest": {
            "type": "object",
            "required": [
                "content"
            ],
            "properties": {
                "additionalInfo": {
                    "description": "Optional additional information for the recipient",
                    "type": "string",
                    "example": "Valid for 24 hours"
                },
                "antiSpamAnswer": {
                    "description": "Answer to the anti-spam question (required if notifications enabled)",
                    "type": "string",
                    "example": "blue"
                },
                "content": {
                    "description": "Secret content to be encrypted",
                    "type": "string",
                    "maxLength": 10000,
                    "minLength": 1,
                    "example": "This is a secret message"
                },
                "expirationHours": {
                    "description": "ExpirationHours specifies a custom expiration in hours. When 0 or omitted, the server default (7 days / 168 hours) applies.\nValid range: 1–2160 (1 hour to 90 days).",
                    "type": "integer",
                    "maximum": 2160,
                    "minimum": 0,
                    "example": 24
                },
                "maxViewCount": {
                    "description": "Maximum number of times the message can be viewed (0 for unlimited)",
                    "type": "integer",
                    "maximum": 100,
                    "minimum": 0,
                    "example": 1
                },
                "passphrase": {
                    "description": "Optional passphrase for additional security",
                    "type": "string",
                    "maxLength": 500,
                    "example": "correct-horse-battery-staple"
                },
                "questionId": {
                    "description": "ID of the anti-spam question",
                    "type": "integer",
                    "example": 0
                },
                "recipient": {
                    "description": "Recipient information (required if notifications enabled)",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.Recipient"
                        }
                    ]
                },
                "sendNotification": {
                    "description": "Whether to send email notifications",
                    "type": "boolean",
                    "example": true
                },
                "sender": {
                    "description": "Sender information (required if notifications enabled)",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.Sender"
                        }
                    ]
                },
                "turnstileToken": {
                    "description": "Cloudflare Turnstile token for verification",
                    "type": "string",
                    "maxLength": 2048
                }
            }
        },
        "models.MessageSubmissionResponse": {
            "type": "object",
            "properties": {
                "decryptUrl": {
                    "description": "API URL to decrypt the message",
                    "type": "string",
                    "example": "https://api.password.exchange/api/v1/messages/123e4567-e89b-12d3-a456-426614174000/decrypt?key=YWJjZGVmZ2hpams="
                },
                "expiresAt": {
                    "description": "When the message will expire",
                    "type": "string"
                },
                "key": {
                    "description": "Base64 encoded encryption key",
                    "type": "string",
                    "example": "YWJjZGVmZ2hpams="
                },
                "messageId": {
                    "description": "Unique identifier for the created message",
                    "type": "string",
                    "example": "123e4567-e89b-12d3-a456-426614174000"
                },
                "notificationSent": {
                    "description": "Whether an email notification was successfully sent",
                    "type": "boolean",
                    "example": true
                },
                "webUrl": {
                    "description": "Web URL for human-friendly access",
                    "type": "string",
                    "example": "https://password.exchange/decrypt/123e4567-e89b-12d3-a456-426614174000/YWJjZGVmZ2hpams="
                }
            }
        },
        "models.Recipient": {
            "type": "object",
            "required": [
                "email"
            ],
            "properties": {
                "email": {
                    "description": "Recipient's email address",
                    "type": "string",
                    "example": "jane@example.com"
                },
                "name": {
                    "description": "Recipient's name",
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 1,
                    "example": "Jane Smith"
                }
            }
        },
        "models.Sender": {
            "type": "object",
            "required": [
                "email",
                "name"
            ],
            "properties": {
                "email": {
                    "description": "Sender's email address",
                    "type": "string",
                    "example": "john@example.com"
                },
                "name": {
                    "description": "Sender's name",
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 1,
                    "example": "John Doe"
                }
            }
        },
        "models.StandardErrorResponse": {
            "type": "object",
            "properties": {
                "details": {
                    "type": "object",
                    "additionalProperties": true
                },
                "error": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "path": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Host:             "password.exchange",
	BasePath:         "/api/v1",
	Schemes:          []string{"https", "http"},
	Title:            "Password Exchange API",
	Description:      "Secure password sharing service that allows users to submit encrypted messages and share them through unique, one-time access URLs.\nThe service provides optional email notifications and passphrase protection for enhanced security.\n\n## Email Reminder System\n\nThe service includes an automated email reminder system that runs via scheduled jobs (CronJob in Kubernetes).\nThis system automatically sends reminder emails to recipients who haven't viewed their secure messages after\na configurable time period. The reminder system is not exposed through REST API endpoints but operates as\na background service with configurable timing, retry logic, and resilience patterns.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
