// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Password Exchange Support",
            "url": "https://github.com/Anthony-Bible/password-exchange"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/files/initiate": {
            "post": {
                "description": "Creates an upload session for a file associated with a message. Returns a fileID, sessionID, and base64url-encoded AES-256 encryption key for use when uploading chunks.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Files"
                ],
                "summary": "Initiate a chunked file upload",
                "parameters": [
                    {
                        "description": "Upload initiation request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.initiateUploadRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "fileID, sessionID, and encodedKey",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Validation error",
                        "schema": {
                            "$ref": "#/definitions/models.StandardErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/models.StandardErrorResponse"
                        }
                    }
                }
            }
        },
        "/files/{fileID}": {
            "get": {
                "description": "Downloads and decrypts a file. The AES-256 decryption key must be supplied via the X-File-Key header as a base64url-encoded string. The key is kept out of the URL to prevent it appearing in server logs or browser history. Direct browser navigation will not work — callers must use fetch() or XMLHttpRequest.",
                "produces": [
                    "application/octet-stream"
                ],
                "tags": [
                    "Files"
                ],
                "summary": "Download a file",
                "parameters": [
                    {
                        "type": "string",
                        "description": "File ID",
                        "name": "fileID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Base64url-encoded AES-256 decryption key",
                        "name": "X-File-Key",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Decrypted file content with Content-Disposition attachment header",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "400": {
                        "description": "Missing or invalid key",
                        "schema": {
                            "$ref": "#/definitions/models.StandardErrorResponse"
                        }
                    },
                    "404": {
                        "description": "File not found",
                        "schema": {
                            "$ref": "#/definitions/models.StandardErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/models.StandardErrorResponse"
                        }
                    }
                }
            }
        },
        "/files/{fileID}/chunks": {
            "post": {
                "description": "Uploads a single chunk as multipart/form-data. Chunks must be uploaded in order starting from index 1. The upload is complete when chunkIndex equals totalChunks.",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Files"
                ],
                "summary": "Upload a file chunk",
                "parameters": [
                    {
                        "type": "string",
                        "description": "File ID returned by the initiate endpoint",
                        "name": "fileID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Upload session ID",
                        "name": "sessionID",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "1-based chunk index",
                        "name": "chunkIndex",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Total number of chunks",
                        "name": "totalChunks",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "Chunk binary data",
                        "name": "data",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "fileID, chunkIndex, and done flag",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Validation error",
                        "schema": {
                            "$ref": "#/definitions/models.StandardErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Upload session not found",
                        "schema": {
                            "$ref": "#/definitions/models.StandardErrorResponse"
                        }
                    },
                    "410": {
                        "description": "Upload session expired",
                        "schema": {
                            "$ref": "#/definitions/models.StandardErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/models.StandardErrorResponse"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Returns the health status of the API and its dependencies",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Utility"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "Service health status",
                        "schema": {
                            "$ref": "#/definitions/models.HealthCheckResponse"
                        }
                    }
                }
            }
        },
        "/info": {
            "get": {
                "description": "Returns information about the API including available endpoints and features",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Utility"
                ],
                "summary": "API information",
                "responses": {
                    "200": {
                        "description": "API information",
                        "schema": {
                            "$ref": "#/definitions/models.APIInfoResponse"
                        }
                    }
                }
            }
        },
        "/messages": {
            "post": {
                "description": "Creates a new encrypted message that can be accessed via a unique URL. Optionally sends email notifications to the recipient.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Messages"
                ],
                "summary": "Submit a new message",
                "parameters": [
                    {
                        "description": "Message submission request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.MessageSubmissionRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Message successfully created",
                        "schema": {
                            "$ref": "#/definitions/models.MessageSubmissionResponse"
                        }
                    },
                    "400": {
                        "description": "Validation error",
                        "schema": {
                            "$ref": "#/definitions/models.StandardErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Anti-spam verification failed",
                        "schema": {
                            "$ref": "#/definitions/models.StandardErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/models.StandardErrorResponse"
                        }
                    }
                }
            }
        },
        "/messages/{id}": {
            "get": {
                "description": "Retrieves information about a message including whether it exists, requires a passphrase, and has been accessed.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Messages"
                ],
                "summary": "Get message access information",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "Message ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "format": "byte",
                        "description": "Base64-encoded decryption key",
                        "name": "key",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Message information retrieved",
                        "schema": {
                            "$ref": "#/definitions/models.MessageAccessInfoResponse"
                        }
                    },
                    "404": {
                        "description": "Message not found or expired",
                        "schema": {
                            "$ref": "#/definitions/models.StandardErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/models.StandardErrorResponse"
                        }
                    }
                }
            }
        },
        "/messages/{id}/decrypt": {
            "post": {
                "description": "Decrypts and retrieves the message content. This is a one-time operation that will delete the message after successful decryption.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Messages"
                ],
                "summary": "Decrypt a message",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "Message ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Decryption request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.MessageDecryptRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Message successfully decrypted",
                        "schema": {
                            "$ref": "#/definitions/models.MessageDecryptResponse"
                        }
                    },
                    "401": {
                        "description": "Invalid passphrase",
                        "schema": {
                            "$ref": "#/definitions/models.StandardErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Message not found or expired",
                        "schema": {
                            "$ref": "#/definitions/models.StandardErrorResponse"
                        }
                    },
                    "410": {
                        "description": "Message already consumed",
                        "schema": {
                            "$ref": "#/definitions/models.StandardErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/models.StandardErrorResponse"
                        }
                    }
                }
            }
        },
        "/messages/{id}/notify": {
            "post": {
                "description": "Sends the email notification for a previously-created message using the caller-supplied ShareURL.\nCall this after any file upload completes so the URL already contains file-download fragment params.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Messages"
                ],
                "summary": "Send deferred email notification for an existing message",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "Message ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Notify request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.MessageNotifyRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Notification sent",
                        "schema": {
                            "$ref": "#/definitions/models.MessageNotifyResponse"
                        }
                    },
                    "400": {
                        "description": "Validation error",
                        "schema": {
                            "$ref": "#/definitions/models.StandardErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Message not found",
                        "schema": {
                            "$ref": "#/definitions/models.StandardErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/models.StandardErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "api.initiateUploadRequest": {
            "type": "object",
            "properties": {
                "chunkSize": {
                    "type": "integer"
                },
                "contentType": {
                    "type": "string"
                },
                "filename": {
                    "type": "string"
                },
                "messageID": {
                    "type": "string"
                },
                "totalSize": {
                    "type": "integer"
                }
            }
        },
        "models.APIInfoResponse": {
            "type": "object",
            "properties": {
                "documentation": {
                    "type": "string"
                },
                "endpoints": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "features": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "boolean"
                    }
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "models.HealthCheckResponse": {
            "type": "object",
            "properties": {
                "services": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "status": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "string"
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "models.MessageAccessInfoResponse": {
            "type": "object",
            "properties": {
                "exists": {
                    "description": "True if the message exists and has not yet been consumed.",
                    "type": "boolean"
                },
                "expiresAt": {
                    "description": "Time at which the message will be automatically deleted. Null for legacy messages.",
                    "type": "string"
                },
                "hasBeenAccessed": {
                    "description": "True if the message has already been viewed at least once.",
                    "type": "boolean"
                },
                "isClientEncrypted": {
                    "description": "True when the stored content is client-side encrypted (E2E mode); decryption happens in the browser.",
                    "type": "boolean"
                },
                "messageId": {
                    "description": "Unique ID of the message.",
                    "type": "string"
                },
                "requiresPassphrase": {
                    "description": "True if the message requires a passphrase before it can be decrypted.",
                    "type": "boolean"
                }
            }
        },
        "models.MessageDecryptRequest": {
            "type": "object",
            "properties": {
                "decryptionKey": {
                    "description": "Optional. Base64url-encoded decryption key. Omit for client-encrypted (E2E) messages\nwhere decryption happens client-side. Max 4096 characters.",
                    "type": "string",
                    "maxLength": 4096
                },
                "passphrase": {
                    "description": "Optional. Passphrase required if the message was created with one.",
                    "type": "string"
                }
            }
        },
        "models.MessageDecryptResponse": {
            "type": "object",
            "properties": {
                "content": {
                    "description": "Decrypted message content. For E2E messages this is the raw ciphertext; the client decrypts it.",
                    "type": "string"
                },
                "decryptedAt": {
                    "description": "Timestamp of this decryption.",
                    "type": "string"
                },
                "expiresAt": {
                    "description": "Time at which the message will be automatically deleted. Null for legacy messages.",
                    "type": "string"
                },
                "isClientEncrypted": {
                    "description": "True when the content is client-side encrypted (E2E mode).",
                    "type": "boolean"
                },
                "maxViewCount": {
                    "description": "Maximum allowed views before deletion. 0 means unlimited.",
                    "type": "integer"
                },
                "messageId": {
                    "description": "Unique ID of the message.",
                    "type": "string"
                },
                "viewCount": {
                    "description": "Number of times this message has been viewed.",
                    "type": "integer"
                }
            }
        },
        "models.MessageNotifyRequest": {
            "type": "object",
            "required": [
                "recipient",
                "sender",
                "shareUrl"
            ],
            "properties": {
                "additionalInfo": {
                    "type": "string"
                },
                "antiSpamAnswer": {
                    "type": "string"
                },
                "questionId": {
                    "type": "integer"
                },
                "recipient": {
                    "$ref": "#/definitions/models.Recipient"
                },
                "sender": {
                    "$ref": "#/definitions/models.Sender"
                },
                "shareUrl": {
                    "type": "string"
                },
                "turnstileToken": {
                    "type": "string",
                    "maxLength": 2048
                }
            }
        },
        "models.MessageNotifyResponse": {
            "type": "object",
            "properties": {
                "notificationSent": {
                    "type": "boolean"
                }
            }
        },
        "models.MessageSubmissionRequest": {
            "type": "object",
            "required": [
                "content"
            ],
            "properties": {
                "additionalInfo": {
                    "description": "Optional. Free-form text included in the notification email body.",
                    "type": "string"
                },
                "antiSpamAnswer": {
                    "description": "Optional. Answer to the anti-spam question identified by questionId.\nRequired when sendNotification is true.",
                    "type": "string"
                },
                "content": {
                    "description": "Required. The message content to encrypt and store. 1–10000 characters.",
                    "type": "string",
                    "minLength": 1
                },
                "e2eKey": {
                    "description": "Optional. Base64url-encoded client-generated AES key for E2E encrypted messages.\nRequired when isClientEncrypted is true and sendNotification is true so the\nemail link includes the #key fragment. Not stored server-side. Max 512 characters.",
                    "type": "string",
                    "maxLength": 512
                },
                "expirationHours": {
                    "description": "Optional. Custom expiration in hours. When 0 or omitted the server default (168 h / 7 days) applies.\nValid range: 1–2160 (1 hour to 90 days).",
                    "type": "integer",
                    "maximum": 2160,
                    "minimum": 0
                },
                "isClientEncrypted": {
                    "description": "Optional. Set to true if the content is already client-side encrypted (E2E mode).\nWhen true, the server stores the ciphertext as-is without re-encrypting.",
                    "type": "boolean"
                },
                "maxViewCount": {
                    "description": "Optional. Maximum number of times the message may be viewed before it is deleted. 0 means unlimited.",
                    "type": "integer",
                    "maximum": 100,
                    "minimum": 0
                },
                "passphrase": {
                    "description": "Optional. Passphrase that the recipient must supply before decrypting. Max 500 characters.",
                    "type": "string",
                    "maxLength": 500
                },
                "questionId": {
                    "description": "Optional. ID of the anti-spam question the user answered.\nRequired when sendNotification is true.",
                    "type": "integer"
                },
                "recipient": {
                    "description": "Optional. Recipient details. Required when sendNotification is true.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.Recipient"
                        }
                    ]
                },
                "sendNotification": {
                    "description": "Optional. Set to true to send an email notification to the recipient.\nRequires sender and recipient to be set.",
                    "type": "boolean"
                },
                "sender": {
                    "description": "Optional. Sender details. Required when sendNotification is true.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.Sender"
                        }
                    ]
                },
                "turnstileToken": {
                    "description": "Optional. Cloudflare Turnstile token for bot protection. Max 2048 characters.",
                    "type": "string",
                    "maxLength": 2048
                }
            }
        },
        "models.MessageSubmissionResponse": {
            "type": "object",
            "properties": {
                "decryptUrl": {
                    "description": "Full URL the recipient should visit to decrypt the message.",
                    "type": "string"
                },
                "expiresAt": {
                    "description": "Time at which the message will be automatically deleted. Null for legacy messages.",
                    "type": "string"
                },
                "isClientEncrypted": {
                    "description": "True when the stored content is client-side encrypted (E2E mode).",
                    "type": "boolean"
                },
                "key": {
                    "description": "Base64url-encoded decryption key. Include this in the share URL fragment so it never reaches the server.",
                    "type": "string"
                },
                "messageId": {
                    "description": "Unique ID of the created message.",
                    "type": "string"
                },
                "notificationSent": {
                    "description": "True if an email notification was successfully sent to the recipient.",
                    "type": "boolean"
                },
                "webUrl": {
                    "description": "Web UI URL for the message (without the key fragment).",
                    "type": "string"
                }
            }
        },
        "models.Recipient": {
            "type": "object",
            "required": [
                "email"
            ],
            "properties": {
                "email": {
                    "description": "Required. Recipient's email address.",
                    "type": "string"
                },
                "name": {
                    "description": "Optional. Recipient's display name. 1–100 characters.",
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 1
                }
            }
        },
        "models.Sender": {
            "type": "object",
            "required": [
                "email",
                "name"
            ],
            "properties": {
                "email": {
                    "description": "Required. Sender's email address.",
                    "type": "string"
                },
                "name": {
                    "description": "Required. Sender's display name. 1–100 characters.",
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 1
                }
            }
        },
        "models.StandardErrorResponse": {
            "type": "object",
            "properties": {
                "details": {
                    "type": "object",
                    "additionalProperties": true
                },
                "error": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "path": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Host:             "password.exchange",
	BasePath:         "/api/v1",
	Schemes:          []string{"https", "http"},
	Title:            "Password Exchange API",
	Description:      "Secure password sharing service that allows users to submit encrypted messages and share them through unique, one-time access URLs.\nThe service provides optional email notifications and passphrase protection for enhanced security.\n\n## Email Reminder System\n\nThe service includes an automated email reminder system that runs via scheduled jobs (CronJob in Kubernetes).\nThis system automatically sends reminder emails to recipients who haven't viewed their secure messages after\na configurable time period. The reminder system is not exposed through REST API endpoints but operates as\na background service with configurable timing, retry logic, and resilience patterns.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
