# Generated by the Protocol Buffers compiler. DO NOT EDIT!
# source: database.proto
# plugin: grpclib.plugin.main
import abc
import typing

import grpclib.const
import grpclib.client
if typing.TYPE_CHECKING:
    import grpclib.server

import google.protobuf.empty_pb2
import database_pb2


class dbServiceBase(abc.ABC):

    @abc.abstractmethod
    async def Select(self, stream: 'grpclib.server.Stream[database_pb2.SelectRequest, database_pb2.SelectResponse]') -> None:
        pass

    @abc.abstractmethod
    async def Insert(self, stream: 'grpclib.server.Stream[database_pb2.InsertRequest, google.protobuf.empty_pb2.Empty]') -> None:
        pass

    @abc.abstractmethod
    async def GetMessage(self, stream: 'grpclib.server.Stream[database_pb2.SelectRequest, database_pb2.SelectResponse]') -> None:
        pass

    def __mapping__(self) -> typing.Dict[str, grpclib.const.Handler]:
        return {
            '/databasepb.dbService/Select': grpclib.const.Handler(
                self.Select,
                grpclib.const.Cardinality.UNARY_UNARY,
                database_pb2.SelectRequest,
                database_pb2.SelectResponse,
            ),
            '/databasepb.dbService/Insert': grpclib.const.Handler(
                self.Insert,
                grpclib.const.Cardinality.UNARY_UNARY,
                database_pb2.InsertRequest,
                google.protobuf.empty_pb2.Empty,
            ),
            '/databasepb.dbService/GetMessage': grpclib.const.Handler(
                self.GetMessage,
                grpclib.const.Cardinality.UNARY_UNARY,
                database_pb2.SelectRequest,
                database_pb2.SelectResponse,
            ),
        }


class dbServiceStub:

    def __init__(self, channel: grpclib.client.Channel) -> None:
        self.Select = grpclib.client.UnaryUnaryMethod(
            channel,
            '/databasepb.dbService/Select',
            database_pb2.SelectRequest,
            database_pb2.SelectResponse,
        )
        self.Insert = grpclib.client.UnaryUnaryMethod(
            channel,
            '/databasepb.dbService/Insert',
            database_pb2.InsertRequest,
            google.protobuf.empty_pb2.Empty,
        )
        self.GetMessage = grpclib.client.UnaryUnaryMethod(
            channel,
            '/databasepb.dbService/GetMessage',
            database_pb2.SelectRequest,
            database_pb2.SelectResponse,
        )
