# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: encryption.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x65ncryption.proto\x12\x0c\x65ncryptionpb\"9\n\x17\x45ncryptedMessageRequest\x12\x11\n\tPlainText\x18\x01 \x03(\t\x12\x0b\n\x03Key\x18\x02 \x01(\x0c\".\n\x18\x45ncryptedMessageResponse\x12\x12\n\nCiphertext\x18\x01 \x03(\t\":\n\x17\x44\x65\x63ryptedMessageRequest\x12\x12\n\nCiphertext\x18\x01 \x03(\t\x12\x0b\n\x03key\x18\x02 \x01(\x0c\"-\n\x18\x44\x65\x63ryptedMessageResponse\x12\x11\n\tplaintext\x18\x01 \x03(\t\"C\n\x0eRandomresponse\x12\x17\n\x0f\x65ncryptionbytes\x18\x01 \x01(\x0c\x12\x18\n\x10\x65ncryptionString\x18\x02 \x01(\t\"%\n\rRandomrequest\x12\x14\n\x0crandomLength\x18\x01 \x01(\x05\x32\xab\x02\n\x0emessageService\x12\x61\n\x0e\x65ncryptMessage\x12%.encryptionpb.EncryptedMessageRequest\x1a&.encryptionpb.EncryptedMessageResponse\"\x00\x12\x61\n\x0e\x44\x65\x63ryptMessage\x12%.encryptionpb.DecryptedMessageRequest\x1a&.encryptionpb.DecryptedMessageResponse\"\x00\x12S\n\x14GenerateRandomString\x12\x1b.encryptionpb.Randomrequest\x1a\x1c.encryptionpb.Randomresponse\"\x00\x42=Z;github.com/Anthony-Bible/password-exchange/app/encryptionpbb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'encryption_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z;github.com/Anthony-Bible/password-exchange/app/encryptionpb'
  _ENCRYPTEDMESSAGEREQUEST._serialized_start=34
  _ENCRYPTEDMESSAGEREQUEST._serialized_end=91
  _ENCRYPTEDMESSAGERESPONSE._serialized_start=93
  _ENCRYPTEDMESSAGERESPONSE._serialized_end=139
  _DECRYPTEDMESSAGEREQUEST._serialized_start=141
  _DECRYPTEDMESSAGEREQUEST._serialized_end=199
  _DECRYPTEDMESSAGERESPONSE._serialized_start=201
  _DECRYPTEDMESSAGERESPONSE._serialized_end=246
  _RANDOMRESPONSE._serialized_start=248
  _RANDOMRESPONSE._serialized_end=315
  _RANDOMREQUEST._serialized_start=317
  _RANDOMREQUEST._serialized_end=354
  _MESSAGESERVICE._serialized_start=357
  _MESSAGESERVICE._serialized_end=656
# @@protoc_insertion_point(module_scope)
