# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: encryption.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'encryption.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x65ncryption.proto\x12\x0c\x65ncryptionpb\":\n\x17\x45ncryptedMessageRequest\x12\x12\n\nplain_text\x18\x01 \x03(\t\x12\x0b\n\x03key\x18\x02 \x01(\x0c\".\n\x18\x45ncryptedMessageResponse\x12\x12\n\nciphertext\x18\x01 \x03(\t\":\n\x17\x44\x65\x63ryptedMessageRequest\x12\x12\n\nciphertext\x18\x01 \x03(\t\x12\x0b\n\x03key\x18\x02 \x01(\x0c\"-\n\x18\x44\x65\x63ryptedMessageResponse\x12\x11\n\tplaintext\x18\x01 \x03(\t\"E\n\x0eRandomresponse\x12\x18\n\x10\x65ncryption_bytes\x18\x01 \x01(\x0c\x12\x19\n\x11\x65ncryption_string\x18\x02 \x01(\t\"&\n\rRandomrequest\x12\x15\n\rrandom_length\x18\x01 \x01(\x05\x32\xab\x02\n\x0eMessageService\x12\x61\n\x0e\x65ncryptMessage\x12%.encryptionpb.EncryptedMessageRequest\x1a&.encryptionpb.EncryptedMessageResponse\"\x00\x12\x61\n\x0e\x44\x65\x63ryptMessage\x12%.encryptionpb.DecryptedMessageRequest\x1a&.encryptionpb.DecryptedMessageResponse\"\x00\x12S\n\x14GenerateRandomString\x12\x1b.encryptionpb.Randomrequest\x1a\x1c.encryptionpb.Randomresponse\"\x00\x42=Z;github.com/Anthony-Bible/password-exchange/app/encryptionpbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'encryption_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z;github.com/Anthony-Bible/password-exchange/app/encryptionpb'
  _globals['_ENCRYPTEDMESSAGEREQUEST']._serialized_start=34
  _globals['_ENCRYPTEDMESSAGEREQUEST']._serialized_end=92
  _globals['_ENCRYPTEDMESSAGERESPONSE']._serialized_start=94
  _globals['_ENCRYPTEDMESSAGERESPONSE']._serialized_end=140
  _globals['_DECRYPTEDMESSAGEREQUEST']._serialized_start=142
  _globals['_DECRYPTEDMESSAGEREQUEST']._serialized_end=200
  _globals['_DECRYPTEDMESSAGERESPONSE']._serialized_start=202
  _globals['_DECRYPTEDMESSAGERESPONSE']._serialized_end=247
  _globals['_RANDOMRESPONSE']._serialized_start=249
  _globals['_RANDOMRESPONSE']._serialized_end=318
  _globals['_RANDOMREQUEST']._serialized_start=320
  _globals['_RANDOMREQUEST']._serialized_end=358
  _globals['_MESSAGESERVICE']._serialized_start=361
  _globals['_MESSAGESERVICE']._serialized_end=660
# @@protoc_insertion_point(module_scope)
