# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import encryption_pb2 as encryption__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in encryption_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MessageServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.encryptMessage = channel.unary_unary(
                '/encryptionpb.MessageService/encryptMessage',
                request_serializer=encryption__pb2.EncryptedMessageRequest.SerializeToString,
                response_deserializer=encryption__pb2.EncryptedMessageResponse.FromString,
                _registered_method=True)
        self.DecryptMessage = channel.unary_unary(
                '/encryptionpb.MessageService/DecryptMessage',
                request_serializer=encryption__pb2.DecryptedMessageRequest.SerializeToString,
                response_deserializer=encryption__pb2.DecryptedMessageResponse.FromString,
                _registered_method=True)
        self.GenerateRandomString = channel.unary_unary(
                '/encryptionpb.MessageService/GenerateRandomString',
                request_serializer=encryption__pb2.Randomrequest.SerializeToString,
                response_deserializer=encryption__pb2.Randomresponse.FromString,
                _registered_method=True)


class MessageServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def encryptMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DecryptMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateRandomString(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MessageServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'encryptMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.encryptMessage,
                    request_deserializer=encryption__pb2.EncryptedMessageRequest.FromString,
                    response_serializer=encryption__pb2.EncryptedMessageResponse.SerializeToString,
            ),
            'DecryptMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.DecryptMessage,
                    request_deserializer=encryption__pb2.DecryptedMessageRequest.FromString,
                    response_serializer=encryption__pb2.DecryptedMessageResponse.SerializeToString,
            ),
            'GenerateRandomString': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateRandomString,
                    request_deserializer=encryption__pb2.Randomrequest.FromString,
                    response_serializer=encryption__pb2.Randomresponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'encryptionpb.MessageService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('encryptionpb.MessageService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MessageService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def encryptMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/encryptionpb.MessageService/encryptMessage',
            encryption__pb2.EncryptedMessageRequest.SerializeToString,
            encryption__pb2.EncryptedMessageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DecryptMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/encryptionpb.MessageService/DecryptMessage',
            encryption__pb2.DecryptedMessageRequest.SerializeToString,
            encryption__pb2.DecryptedMessageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateRandomString(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/encryptionpb.MessageService/GenerateRandomString',
            encryption__pb2.Randomrequest.SerializeToString,
            encryption__pb2.Randomresponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
