# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rmessage.proto\x12\tmessagepb\"\xcf\x01\n\x07Message\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x11\n\tfirstname\x18\x02 \x01(\t\x12\x16\n\x0eotherfirstname\x18\x03 \x01(\t\x12\x15\n\rOtherLastName\x18\x04 \x01(\t\x12\x12\n\nOtherEmail\x18\x05 \x01(\t\x12\x10\n\x08Uniqueid\x18\x06 \x01(\t\x12\x0f\n\x07\x43ontent\x18\x07 \x01(\t\x12\x0e\n\x06\x45rrors\x18\x08 \x01(\t\x12\x0b\n\x03Url\x18\t \x01(\t\x12\x0e\n\x06Hidden\x18\n \x01(\t\x12\x0f\n\x07\x43\x61ptcha\x18\x0b \x01(\tB:Z8github.com/Anthony-Bible/password-exchange/app/messagepbb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'message_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z8github.com/Anthony-Bible/password-exchange/app/messagepb'
  _MESSAGE._serialized_start=29
  _MESSAGE._serialized_end=236
# @@protoc_insertion_point(module_scope)
