# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: message.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'message.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rmessage.proto\x12\tmessagepb\"\xd6\x01\n\x07Message\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x12\n\nfirst_name\x18\x02 \x01(\t\x12\x18\n\x10other_first_name\x18\x03 \x01(\t\x12\x17\n\x0fother_last_name\x18\x04 \x01(\t\x12\x13\n\x0bother_email\x18\x05 \x01(\t\x12\x11\n\tunique_id\x18\x06 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x07 \x01(\t\x12\x0e\n\x06\x65rrors\x18\x08 \x01(\t\x12\x0b\n\x03url\x18\t \x01(\t\x12\x0e\n\x06hidden\x18\n \x01(\t\x12\x0f\n\x07\x63\x61ptcha\x18\x0b \x01(\tB:Z8github.com/Anthony-Bible/password-exchange/app/messagepbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'message_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z8github.com/Anthony-Bible/password-exchange/app/messagepb'
  _globals['_MESSAGE']._serialized_start=29
  _globals['_MESSAGE']._serialized_end=243
# @@protoc_insertion_point(module_scope)
