---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: slackbot-deployment
  namespace: default
  labels:
    app: pe_slackbot 
spec:
  selector:
    matchLabels:
      app: pe_slackbot 
  replicas: 2
  template: 
    metadata:
      labels:
        app: pe_slackbot 
        name: "slackbot"
        phase: "prod" 
      annotations:
        iam.amazonaws.com/role: arn:aws:iam::842805395457:role/Test_ec2ForSDK
    spec:
      containers:
      - name: slackbot 
        image:  ghcr.io/anthony-bible/slackbot-container-prod:0.0.17
        envFrom:
          - secretRef:
              name: slackbot-creds 
      imagePullSecrets:
      - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: slackbot-service 
  annotations:
    # external-dns.alpha.kubernetes.io/hostname: anthony.bible
  namespace: default
spec:
  selector:
    app: pe_slackbot 
  ports:
    - name: http
      port: 80
      targetPort: 8080
      
---

