// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: message.proto

package messagepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Message struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Email          string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Firstname      string                 `protobuf:"bytes,2,opt,name=firstname,proto3" json:"firstname,omitempty"`
	Otherfirstname string                 `protobuf:"bytes,3,opt,name=otherfirstname,proto3" json:"otherfirstname,omitempty"`
	OtherLastName  string                 `protobuf:"bytes,4,opt,name=OtherLastName,proto3" json:"OtherLastName,omitempty"`
	OtherEmail     string                 `protobuf:"bytes,5,opt,name=OtherEmail,proto3" json:"OtherEmail,omitempty"`
	Uniqueid       string                 `protobuf:"bytes,6,opt,name=Uniqueid,proto3" json:"Uniqueid,omitempty"`
	Content        string                 `protobuf:"bytes,7,opt,name=Content,proto3" json:"Content,omitempty"`
	Errors         string                 `protobuf:"bytes,8,opt,name=Errors,proto3" json:"Errors,omitempty"`
	Url            string                 `protobuf:"bytes,9,opt,name=Url,proto3" json:"Url,omitempty"`
	Hidden         string                 `protobuf:"bytes,10,opt,name=Hidden,proto3" json:"Hidden,omitempty"`
	Captcha        string                 `protobuf:"bytes,11,opt,name=Captcha,proto3" json:"Captcha,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Message) GetFirstname() string {
	if x != nil {
		return x.Firstname
	}
	return ""
}

func (x *Message) GetOtherfirstname() string {
	if x != nil {
		return x.Otherfirstname
	}
	return ""
}

func (x *Message) GetOtherLastName() string {
	if x != nil {
		return x.OtherLastName
	}
	return ""
}

func (x *Message) GetOtherEmail() string {
	if x != nil {
		return x.OtherEmail
	}
	return ""
}

func (x *Message) GetUniqueid() string {
	if x != nil {
		return x.Uniqueid
	}
	return ""
}

func (x *Message) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Message) GetErrors() string {
	if x != nil {
		return x.Errors
	}
	return ""
}

func (x *Message) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Message) GetHidden() string {
	if x != nil {
		return x.Hidden
	}
	return ""
}

func (x *Message) GetCaptcha() string {
	if x != nil {
		return x.Captcha
	}
	return ""
}

var File_message_proto protoreflect.FileDescriptor

const file_message_proto_rawDesc = "" +
	"\n" +
	"\rmessage.proto\x12\tmessagepb\"\xbd\x02\n" +
	"\aMessage\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1c\n" +
	"\tfirstname\x18\x02 \x01(\tR\tfirstname\x12&\n" +
	"\x0eotherfirstname\x18\x03 \x01(\tR\x0eotherfirstname\x12$\n" +
	"\rOtherLastName\x18\x04 \x01(\tR\rOtherLastName\x12\x1e\n" +
	"\n" +
	"OtherEmail\x18\x05 \x01(\tR\n" +
	"OtherEmail\x12\x1a\n" +
	"\bUniqueid\x18\x06 \x01(\tR\bUniqueid\x12\x18\n" +
	"\aContent\x18\a \x01(\tR\aContent\x12\x16\n" +
	"\x06Errors\x18\b \x01(\tR\x06Errors\x12\x10\n" +
	"\x03Url\x18\t \x01(\tR\x03Url\x12\x16\n" +
	"\x06Hidden\x18\n" +
	" \x01(\tR\x06Hidden\x12\x18\n" +
	"\aCaptcha\x18\v \x01(\tR\aCaptchaB:Z8github.com/Anthony-Bible/password-exchange/app/messagepbb\x06proto3"

var (
	file_message_proto_rawDescOnce sync.Once
	file_message_proto_rawDescData []byte
)

func file_message_proto_rawDescGZIP() []byte {
	file_message_proto_rawDescOnce.Do(func() {
		file_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_message_proto_rawDesc), len(file_message_proto_rawDesc)))
	})
	return file_message_proto_rawDescData
}

var file_message_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_message_proto_goTypes = []any{
	(*Message)(nil), // 0: messagepb.Message
}
var file_message_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_message_proto_init() }
func file_message_proto_init() {
	if File_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_message_proto_rawDesc), len(file_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_message_proto_goTypes,
		DependencyIndexes: file_message_proto_depIdxs,
		MessageInfos:      file_message_proto_msgTypes,
	}.Build()
	File_message_proto = out.File
	file_message_proto_goTypes = nil
	file_message_proto_depIdxs = nil
}
