// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.27.3
// source: database.proto

package databasepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DbService_Select_FullMethodName                          = "/databasepb.dbService/Select"
	DbService_Insert_FullMethodName                          = "/databasepb.dbService/Insert"
	DbService_GetMessage_FullMethodName                      = "/databasepb.dbService/GetMessage"
	DbService_GetUnviewedMessagesForReminders_FullMethodName = "/databasepb.dbService/GetUnviewedMessagesForReminders"
	DbService_LogReminderSent_FullMethodName                 = "/databasepb.dbService/LogReminderSent"
	DbService_GetReminderHistory_FullMethodName              = "/databasepb.dbService/GetReminderHistory"
	DbService_CreateUploadSession_FullMethodName             = "/databasepb.dbService/CreateUploadSession"
	DbService_GetUploadSession_FullMethodName                = "/databasepb.dbService/GetUploadSession"
	DbService_AddCompletedPart_FullMethodName                = "/databasepb.dbService/AddCompletedPart"
	DbService_CompleteUploadSession_FullMethodName           = "/databasepb.dbService/CompleteUploadSession"
	DbService_DeleteUploadSession_FullMethodName             = "/databasepb.dbService/DeleteUploadSession"
	DbService_DeleteExpiredUploadSessions_FullMethodName     = "/databasepb.dbService/DeleteExpiredUploadSessions"
)

// DbServiceClient is the client API for DbService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DbServiceClient interface {
	Select(ctx context.Context, in *SelectRequest, opts ...grpc.CallOption) (*SelectResponse, error)
	Insert(ctx context.Context, in *InsertRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetMessage(ctx context.Context, in *SelectRequest, opts ...grpc.CallOption) (*SelectResponse, error)
	GetUnviewedMessagesForReminders(ctx context.Context, in *GetUnviewedMessagesRequest, opts ...grpc.CallOption) (*GetUnviewedMessagesResponse, error)
	LogReminderSent(ctx context.Context, in *LogReminderRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetReminderHistory(ctx context.Context, in *GetReminderHistoryRequest, opts ...grpc.CallOption) (*GetReminderHistoryResponse, error)
	// Upload-session RPCs — the database service owns the file_upload_sessions
	// table and all SQL for it.  The web service must call these instead of
	// reaching MySQL directly.
	CreateUploadSession(ctx context.Context, in *CreateUploadSessionRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetUploadSession(ctx context.Context, in *GetUploadSessionRequest, opts ...grpc.CallOption) (*GetUploadSessionResponse, error)
	AddCompletedPart(ctx context.Context, in *AddCompletedPartRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	CompleteUploadSession(ctx context.Context, in *CompleteUploadSessionRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	DeleteUploadSession(ctx context.Context, in *DeleteUploadSessionRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	DeleteExpiredUploadSessions(ctx context.Context, in *DeleteExpiredUploadSessionsRequest, opts ...grpc.CallOption) (*DeleteExpiredUploadSessionsResponse, error)
}

type dbServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDbServiceClient(cc grpc.ClientConnInterface) DbServiceClient {
	return &dbServiceClient{cc}
}

func (c *dbServiceClient) Select(ctx context.Context, in *SelectRequest, opts ...grpc.CallOption) (*SelectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SelectResponse)
	err := c.cc.Invoke(ctx, DbService_Select_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dbServiceClient) Insert(ctx context.Context, in *InsertRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, DbService_Insert_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dbServiceClient) GetMessage(ctx context.Context, in *SelectRequest, opts ...grpc.CallOption) (*SelectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SelectResponse)
	err := c.cc.Invoke(ctx, DbService_GetMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dbServiceClient) GetUnviewedMessagesForReminders(ctx context.Context, in *GetUnviewedMessagesRequest, opts ...grpc.CallOption) (*GetUnviewedMessagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUnviewedMessagesResponse)
	err := c.cc.Invoke(ctx, DbService_GetUnviewedMessagesForReminders_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dbServiceClient) LogReminderSent(ctx context.Context, in *LogReminderRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, DbService_LogReminderSent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dbServiceClient) GetReminderHistory(ctx context.Context, in *GetReminderHistoryRequest, opts ...grpc.CallOption) (*GetReminderHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetReminderHistoryResponse)
	err := c.cc.Invoke(ctx, DbService_GetReminderHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dbServiceClient) CreateUploadSession(ctx context.Context, in *CreateUploadSessionRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, DbService_CreateUploadSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dbServiceClient) GetUploadSession(ctx context.Context, in *GetUploadSessionRequest, opts ...grpc.CallOption) (*GetUploadSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUploadSessionResponse)
	err := c.cc.Invoke(ctx, DbService_GetUploadSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dbServiceClient) AddCompletedPart(ctx context.Context, in *AddCompletedPartRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, DbService_AddCompletedPart_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dbServiceClient) CompleteUploadSession(ctx context.Context, in *CompleteUploadSessionRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, DbService_CompleteUploadSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dbServiceClient) DeleteUploadSession(ctx context.Context, in *DeleteUploadSessionRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, DbService_DeleteUploadSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dbServiceClient) DeleteExpiredUploadSessions(ctx context.Context, in *DeleteExpiredUploadSessionsRequest, opts ...grpc.CallOption) (*DeleteExpiredUploadSessionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteExpiredUploadSessionsResponse)
	err := c.cc.Invoke(ctx, DbService_DeleteExpiredUploadSessions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DbServiceServer is the server API for DbService service.
// All implementations must embed UnimplementedDbServiceServer
// for forward compatibility.
type DbServiceServer interface {
	Select(context.Context, *SelectRequest) (*SelectResponse, error)
	Insert(context.Context, *InsertRequest) (*emptypb.Empty, error)
	GetMessage(context.Context, *SelectRequest) (*SelectResponse, error)
	GetUnviewedMessagesForReminders(context.Context, *GetUnviewedMessagesRequest) (*GetUnviewedMessagesResponse, error)
	LogReminderSent(context.Context, *LogReminderRequest) (*emptypb.Empty, error)
	GetReminderHistory(context.Context, *GetReminderHistoryRequest) (*GetReminderHistoryResponse, error)
	// Upload-session RPCs — the database service owns the file_upload_sessions
	// table and all SQL for it.  The web service must call these instead of
	// reaching MySQL directly.
	CreateUploadSession(context.Context, *CreateUploadSessionRequest) (*emptypb.Empty, error)
	GetUploadSession(context.Context, *GetUploadSessionRequest) (*GetUploadSessionResponse, error)
	AddCompletedPart(context.Context, *AddCompletedPartRequest) (*emptypb.Empty, error)
	CompleteUploadSession(context.Context, *CompleteUploadSessionRequest) (*emptypb.Empty, error)
	DeleteUploadSession(context.Context, *DeleteUploadSessionRequest) (*emptypb.Empty, error)
	DeleteExpiredUploadSessions(context.Context, *DeleteExpiredUploadSessionsRequest) (*DeleteExpiredUploadSessionsResponse, error)
	mustEmbedUnimplementedDbServiceServer()
}

// UnimplementedDbServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDbServiceServer struct{}

func (UnimplementedDbServiceServer) Select(context.Context, *SelectRequest) (*SelectResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Select not implemented")
}
func (UnimplementedDbServiceServer) Insert(context.Context, *InsertRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Insert not implemented")
}
func (UnimplementedDbServiceServer) GetMessage(context.Context, *SelectRequest) (*SelectResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMessage not implemented")
}
func (UnimplementedDbServiceServer) GetUnviewedMessagesForReminders(context.Context, *GetUnviewedMessagesRequest) (*GetUnviewedMessagesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUnviewedMessagesForReminders not implemented")
}
func (UnimplementedDbServiceServer) LogReminderSent(context.Context, *LogReminderRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LogReminderSent not implemented")
}
func (UnimplementedDbServiceServer) GetReminderHistory(context.Context, *GetReminderHistoryRequest) (*GetReminderHistoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetReminderHistory not implemented")
}
func (UnimplementedDbServiceServer) CreateUploadSession(context.Context, *CreateUploadSessionRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUploadSession not implemented")
}
func (UnimplementedDbServiceServer) GetUploadSession(context.Context, *GetUploadSessionRequest) (*GetUploadSessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUploadSession not implemented")
}
func (UnimplementedDbServiceServer) AddCompletedPart(context.Context, *AddCompletedPartRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddCompletedPart not implemented")
}
func (UnimplementedDbServiceServer) CompleteUploadSession(context.Context, *CompleteUploadSessionRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CompleteUploadSession not implemented")
}
func (UnimplementedDbServiceServer) DeleteUploadSession(context.Context, *DeleteUploadSessionRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteUploadSession not implemented")
}
func (UnimplementedDbServiceServer) DeleteExpiredUploadSessions(context.Context, *DeleteExpiredUploadSessionsRequest) (*DeleteExpiredUploadSessionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteExpiredUploadSessions not implemented")
}
func (UnimplementedDbServiceServer) mustEmbedUnimplementedDbServiceServer() {}
func (UnimplementedDbServiceServer) testEmbeddedByValue()                   {}

// UnsafeDbServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DbServiceServer will
// result in compilation errors.
type UnsafeDbServiceServer interface {
	mustEmbedUnimplementedDbServiceServer()
}

func RegisterDbServiceServer(s grpc.ServiceRegistrar, srv DbServiceServer) {
	// If the following call panics, it indicates UnimplementedDbServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DbService_ServiceDesc, srv)
}

func _DbService_Select_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SelectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DbServiceServer).Select(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DbService_Select_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DbServiceServer).Select(ctx, req.(*SelectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DbService_Insert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InsertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DbServiceServer).Insert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DbService_Insert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DbServiceServer).Insert(ctx, req.(*InsertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DbService_GetMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SelectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DbServiceServer).GetMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DbService_GetMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DbServiceServer).GetMessage(ctx, req.(*SelectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DbService_GetUnviewedMessagesForReminders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUnviewedMessagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DbServiceServer).GetUnviewedMessagesForReminders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DbService_GetUnviewedMessagesForReminders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DbServiceServer).GetUnviewedMessagesForReminders(ctx, req.(*GetUnviewedMessagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DbService_LogReminderSent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogReminderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DbServiceServer).LogReminderSent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DbService_LogReminderSent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DbServiceServer).LogReminderSent(ctx, req.(*LogReminderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DbService_GetReminderHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetReminderHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DbServiceServer).GetReminderHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DbService_GetReminderHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DbServiceServer).GetReminderHistory(ctx, req.(*GetReminderHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DbService_CreateUploadSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUploadSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DbServiceServer).CreateUploadSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DbService_CreateUploadSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DbServiceServer).CreateUploadSession(ctx, req.(*CreateUploadSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DbService_GetUploadSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUploadSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DbServiceServer).GetUploadSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DbService_GetUploadSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DbServiceServer).GetUploadSession(ctx, req.(*GetUploadSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DbService_AddCompletedPart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddCompletedPartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DbServiceServer).AddCompletedPart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DbService_AddCompletedPart_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DbServiceServer).AddCompletedPart(ctx, req.(*AddCompletedPartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DbService_CompleteUploadSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompleteUploadSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DbServiceServer).CompleteUploadSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DbService_CompleteUploadSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DbServiceServer).CompleteUploadSession(ctx, req.(*CompleteUploadSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DbService_DeleteUploadSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteUploadSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DbServiceServer).DeleteUploadSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DbService_DeleteUploadSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DbServiceServer).DeleteUploadSession(ctx, req.(*DeleteUploadSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DbService_DeleteExpiredUploadSessions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteExpiredUploadSessionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DbServiceServer).DeleteExpiredUploadSessions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DbService_DeleteExpiredUploadSessions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DbServiceServer).DeleteExpiredUploadSessions(ctx, req.(*DeleteExpiredUploadSessionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DbService_ServiceDesc is the grpc.ServiceDesc for DbService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DbService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "databasepb.dbService",
	HandlerType: (*DbServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Select",
			Handler:    _DbService_Select_Handler,
		},
		{
			MethodName: "Insert",
			Handler:    _DbService_Insert_Handler,
		},
		{
			MethodName: "GetMessage",
			Handler:    _DbService_GetMessage_Handler,
		},
		{
			MethodName: "GetUnviewedMessagesForReminders",
			Handler:    _DbService_GetUnviewedMessagesForReminders_Handler,
		},
		{
			MethodName: "LogReminderSent",
			Handler:    _DbService_LogReminderSent_Handler,
		},
		{
			MethodName: "GetReminderHistory",
			Handler:    _DbService_GetReminderHistory_Handler,
		},
		{
			MethodName: "CreateUploadSession",
			Handler:    _DbService_CreateUploadSession_Handler,
		},
		{
			MethodName: "GetUploadSession",
			Handler:    _DbService_GetUploadSession_Handler,
		},
		{
			MethodName: "AddCompletedPart",
			Handler:    _DbService_AddCompletedPart_Handler,
		},
		{
			MethodName: "CompleteUploadSession",
			Handler:    _DbService_CompleteUploadSession_Handler,
		},
		{
			MethodName: "DeleteUploadSession",
			Handler:    _DbService_DeleteUploadSession_Handler,
		},
		{
			MethodName: "DeleteExpiredUploadSessions",
			Handler:    _DbService_DeleteExpiredUploadSessions_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "database.proto",
}
