// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: database.proto

package databasepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SelectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SelectRequest) Reset() {
	*x = SelectRequest{}
	mi := &file_database_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SelectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelectRequest) ProtoMessage() {}

func (x *SelectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_database_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SelectRequest.ProtoReflect.Descriptor instead.
func (*SelectRequest) Descriptor() ([]byte, []int) {
	return file_database_proto_rawDescGZIP(), []int{0}
}

func (x *SelectRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type SelectResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Uuid              string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Content           string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Passphrase        string                 `protobuf:"bytes,3,opt,name=passphrase,proto3" json:"passphrase,omitempty"`
	ViewCount         int32                  `protobuf:"varint,4,opt,name=view_count,json=viewCount,proto3" json:"view_count,omitempty"`
	MaxViewCount      int32                  `protobuf:"varint,5,opt,name=max_view_count,json=maxViewCount,proto3" json:"max_view_count,omitempty"`
	ExpiresAt         string                 `protobuf:"bytes,6,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"` // RFC3339 timestamp
	IsClientEncrypted bool                   `protobuf:"varint,7,opt,name=is_client_encrypted,json=isClientEncrypted,proto3" json:"is_client_encrypted,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SelectResponse) Reset() {
	*x = SelectResponse{}
	mi := &file_database_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SelectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelectResponse) ProtoMessage() {}

func (x *SelectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_database_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SelectResponse.ProtoReflect.Descriptor instead.
func (*SelectResponse) Descriptor() ([]byte, []int) {
	return file_database_proto_rawDescGZIP(), []int{1}
}

func (x *SelectResponse) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *SelectResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *SelectResponse) GetPassphrase() string {
	if x != nil {
		return x.Passphrase
	}
	return ""
}

func (x *SelectResponse) GetViewCount() int32 {
	if x != nil {
		return x.ViewCount
	}
	return 0
}

func (x *SelectResponse) GetMaxViewCount() int32 {
	if x != nil {
		return x.MaxViewCount
	}
	return 0
}

func (x *SelectResponse) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

func (x *SelectResponse) GetIsClientEncrypted() bool {
	if x != nil {
		return x.IsClientEncrypted
	}
	return false
}

type InsertRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Uuid              string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Content           string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Passphrase        string                 `protobuf:"bytes,3,opt,name=passphrase,proto3" json:"passphrase,omitempty"`
	MaxViewCount      int32                  `protobuf:"varint,4,opt,name=max_view_count,json=maxViewCount,proto3" json:"max_view_count,omitempty"`
	RecipientEmail    string                 `protobuf:"bytes,5,opt,name=recipient_email,json=recipientEmail,proto3" json:"recipient_email,omitempty"`
	ExpiresAt         string                 `protobuf:"bytes,6,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"` // RFC3339 timestamp; empty means use server default TTL
	IsClientEncrypted bool                   `protobuf:"varint,7,opt,name=is_client_encrypted,json=isClientEncrypted,proto3" json:"is_client_encrypted,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *InsertRequest) Reset() {
	*x = InsertRequest{}
	mi := &file_database_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertRequest) ProtoMessage() {}

func (x *InsertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_database_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertRequest.ProtoReflect.Descriptor instead.
func (*InsertRequest) Descriptor() ([]byte, []int) {
	return file_database_proto_rawDescGZIP(), []int{2}
}

func (x *InsertRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *InsertRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *InsertRequest) GetPassphrase() string {
	if x != nil {
		return x.Passphrase
	}
	return ""
}

func (x *InsertRequest) GetMaxViewCount() int32 {
	if x != nil {
		return x.MaxViewCount
	}
	return 0
}

func (x *InsertRequest) GetRecipientEmail() string {
	if x != nil {
		return x.RecipientEmail
	}
	return ""
}

func (x *InsertRequest) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

func (x *InsertRequest) GetIsClientEncrypted() bool {
	if x != nil {
		return x.IsClientEncrypted
	}
	return false
}

type GetUnviewedMessagesRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	OlderThanHours        int32                  `protobuf:"varint,1,opt,name=older_than_hours,json=olderThanHours,proto3" json:"older_than_hours,omitempty"`
	MaxReminders          int32                  `protobuf:"varint,2,opt,name=max_reminders,json=maxReminders,proto3" json:"max_reminders,omitempty"`
	ReminderIntervalHours int32                  `protobuf:"varint,3,opt,name=reminder_interval_hours,json=reminderIntervalHours,proto3" json:"reminder_interval_hours,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *GetUnviewedMessagesRequest) Reset() {
	*x = GetUnviewedMessagesRequest{}
	mi := &file_database_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUnviewedMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUnviewedMessagesRequest) ProtoMessage() {}

func (x *GetUnviewedMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_database_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUnviewedMessagesRequest.ProtoReflect.Descriptor instead.
func (*GetUnviewedMessagesRequest) Descriptor() ([]byte, []int) {
	return file_database_proto_rawDescGZIP(), []int{3}
}

func (x *GetUnviewedMessagesRequest) GetOlderThanHours() int32 {
	if x != nil {
		return x.OlderThanHours
	}
	return 0
}

func (x *GetUnviewedMessagesRequest) GetMaxReminders() int32 {
	if x != nil {
		return x.MaxReminders
	}
	return 0
}

func (x *GetUnviewedMessagesRequest) GetReminderIntervalHours() int32 {
	if x != nil {
		return x.ReminderIntervalHours
	}
	return 0
}

type UnviewedMessage struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MessageId      int32                  `protobuf:"varint,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	UniqueId       string                 `protobuf:"bytes,2,opt,name=unique_id,json=uniqueId,proto3" json:"unique_id,omitempty"`
	RecipientEmail string                 `protobuf:"bytes,3,opt,name=recipient_email,json=recipientEmail,proto3" json:"recipient_email,omitempty"`
	Created        string                 `protobuf:"bytes,4,opt,name=created,proto3" json:"created,omitempty"`
	DaysOld        int32                  `protobuf:"varint,5,opt,name=days_old,json=daysOld,proto3" json:"days_old,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UnviewedMessage) Reset() {
	*x = UnviewedMessage{}
	mi := &file_database_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnviewedMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnviewedMessage) ProtoMessage() {}

func (x *UnviewedMessage) ProtoReflect() protoreflect.Message {
	mi := &file_database_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnviewedMessage.ProtoReflect.Descriptor instead.
func (*UnviewedMessage) Descriptor() ([]byte, []int) {
	return file_database_proto_rawDescGZIP(), []int{4}
}

func (x *UnviewedMessage) GetMessageId() int32 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

func (x *UnviewedMessage) GetUniqueId() string {
	if x != nil {
		return x.UniqueId
	}
	return ""
}

func (x *UnviewedMessage) GetRecipientEmail() string {
	if x != nil {
		return x.RecipientEmail
	}
	return ""
}

func (x *UnviewedMessage) GetCreated() string {
	if x != nil {
		return x.Created
	}
	return ""
}

func (x *UnviewedMessage) GetDaysOld() int32 {
	if x != nil {
		return x.DaysOld
	}
	return 0
}

type GetUnviewedMessagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*UnviewedMessage     `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUnviewedMessagesResponse) Reset() {
	*x = GetUnviewedMessagesResponse{}
	mi := &file_database_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUnviewedMessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUnviewedMessagesResponse) ProtoMessage() {}

func (x *GetUnviewedMessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_database_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUnviewedMessagesResponse.ProtoReflect.Descriptor instead.
func (*GetUnviewedMessagesResponse) Descriptor() ([]byte, []int) {
	return file_database_proto_rawDescGZIP(), []int{5}
}

func (x *GetUnviewedMessagesResponse) GetMessages() []*UnviewedMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

type LogReminderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     int32                  `protobuf:"varint,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	EmailAddress  string                 `protobuf:"bytes,2,opt,name=email_address,json=emailAddress,proto3" json:"email_address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogReminderRequest) Reset() {
	*x = LogReminderRequest{}
	mi := &file_database_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogReminderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogReminderRequest) ProtoMessage() {}

func (x *LogReminderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_database_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogReminderRequest.ProtoReflect.Descriptor instead.
func (*LogReminderRequest) Descriptor() ([]byte, []int) {
	return file_database_proto_rawDescGZIP(), []int{6}
}

func (x *LogReminderRequest) GetMessageId() int32 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

func (x *LogReminderRequest) GetEmailAddress() string {
	if x != nil {
		return x.EmailAddress
	}
	return ""
}

type GetReminderHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     int32                  `protobuf:"varint,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReminderHistoryRequest) Reset() {
	*x = GetReminderHistoryRequest{}
	mi := &file_database_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReminderHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReminderHistoryRequest) ProtoMessage() {}

func (x *GetReminderHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_database_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReminderHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetReminderHistoryRequest) Descriptor() ([]byte, []int) {
	return file_database_proto_rawDescGZIP(), []int{7}
}

func (x *GetReminderHistoryRequest) GetMessageId() int32 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

type ReminderLogEntry struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	MessageId        int32                  `protobuf:"varint,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	EmailAddress     string                 `protobuf:"bytes,2,opt,name=email_address,json=emailAddress,proto3" json:"email_address,omitempty"`
	ReminderCount    int32                  `protobuf:"varint,3,opt,name=reminder_count,json=reminderCount,proto3" json:"reminder_count,omitempty"`
	LastReminderSent string                 `protobuf:"bytes,4,opt,name=last_reminder_sent,json=lastReminderSent,proto3" json:"last_reminder_sent,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ReminderLogEntry) Reset() {
	*x = ReminderLogEntry{}
	mi := &file_database_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReminderLogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReminderLogEntry) ProtoMessage() {}

func (x *ReminderLogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_database_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReminderLogEntry.ProtoReflect.Descriptor instead.
func (*ReminderLogEntry) Descriptor() ([]byte, []int) {
	return file_database_proto_rawDescGZIP(), []int{8}
}

func (x *ReminderLogEntry) GetMessageId() int32 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

func (x *ReminderLogEntry) GetEmailAddress() string {
	if x != nil {
		return x.EmailAddress
	}
	return ""
}

func (x *ReminderLogEntry) GetReminderCount() int32 {
	if x != nil {
		return x.ReminderCount
	}
	return 0
}

func (x *ReminderLogEntry) GetLastReminderSent() string {
	if x != nil {
		return x.LastReminderSent
	}
	return ""
}

type GetReminderHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*ReminderLogEntry    `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReminderHistoryResponse) Reset() {
	*x = GetReminderHistoryResponse{}
	mi := &file_database_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReminderHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReminderHistoryResponse) ProtoMessage() {}

func (x *GetReminderHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_database_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReminderHistoryResponse.ProtoReflect.Descriptor instead.
func (*GetReminderHistoryResponse) Descriptor() ([]byte, []int) {
	return file_database_proto_rawDescGZIP(), []int{9}
}

func (x *GetReminderHistoryResponse) GetEntries() []*ReminderLogEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

// UploadSessionPart represents a single successfully uploaded multipart part.
type UploadSessionPart struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PartNumber    int32                  `protobuf:"varint,1,opt,name=part_number,json=partNumber,proto3" json:"part_number,omitempty"`
	Etag          string                 `protobuf:"bytes,2,opt,name=etag,proto3" json:"etag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadSessionPart) Reset() {
	*x = UploadSessionPart{}
	mi := &file_database_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadSessionPart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadSessionPart) ProtoMessage() {}

func (x *UploadSessionPart) ProtoReflect() protoreflect.Message {
	mi := &file_database_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadSessionPart.ProtoReflect.Descriptor instead.
func (*UploadSessionPart) Descriptor() ([]byte, []int) {
	return file_database_proto_rawDescGZIP(), []int{10}
}

func (x *UploadSessionPart) GetPartNumber() int32 {
	if x != nil {
		return x.PartNumber
	}
	return 0
}

func (x *UploadSessionPart) GetEtag() string {
	if x != nil {
		return x.Etag
	}
	return ""
}

// UploadSession is the wire representation of a file_upload_sessions row.
// encryption_key is absent (empty bytes) for completed sessions where the
// server has already cleared the key at rest.
type UploadSession struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SessionId      string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	FileId         string                 `protobuf:"bytes,2,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	MessageId      string                 `protobuf:"bytes,3,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	UploadId       string                 `protobuf:"bytes,4,opt,name=upload_id,json=uploadId,proto3" json:"upload_id,omitempty"`
	Filename       string                 `protobuf:"bytes,5,opt,name=filename,proto3" json:"filename,omitempty"`
	ContentType    string                 `protobuf:"bytes,6,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	TotalSize      int64                  `protobuf:"varint,7,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"`
	TotalChunks    int32                  `protobuf:"varint,8,opt,name=total_chunks,json=totalChunks,proto3" json:"total_chunks,omitempty"`
	Status         string                 `protobuf:"bytes,9,opt,name=status,proto3" json:"status,omitempty"`
	EncryptionKey  []byte                 `protobuf:"bytes,10,opt,name=encryption_key,json=encryptionKey,proto3" json:"encryption_key,omitempty"` // empty for completed sessions
	CompletedParts []*UploadSessionPart   `protobuf:"bytes,11,rep,name=completed_parts,json=completedParts,proto3" json:"completed_parts,omitempty"`
	CreatedAt      string                 `protobuf:"bytes,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // RFC3339 timestamp
	ExpiresAt      string                 `protobuf:"bytes,13,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"` // RFC3339 timestamp
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UploadSession) Reset() {
	*x = UploadSession{}
	mi := &file_database_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadSession) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadSession) ProtoMessage() {}

func (x *UploadSession) ProtoReflect() protoreflect.Message {
	mi := &file_database_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadSession.ProtoReflect.Descriptor instead.
func (*UploadSession) Descriptor() ([]byte, []int) {
	return file_database_proto_rawDescGZIP(), []int{11}
}

func (x *UploadSession) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *UploadSession) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *UploadSession) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *UploadSession) GetUploadId() string {
	if x != nil {
		return x.UploadId
	}
	return ""
}

func (x *UploadSession) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *UploadSession) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *UploadSession) GetTotalSize() int64 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

func (x *UploadSession) GetTotalChunks() int32 {
	if x != nil {
		return x.TotalChunks
	}
	return 0
}

func (x *UploadSession) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UploadSession) GetEncryptionKey() []byte {
	if x != nil {
		return x.EncryptionKey
	}
	return nil
}

func (x *UploadSession) GetCompletedParts() []*UploadSessionPart {
	if x != nil {
		return x.CompletedParts
	}
	return nil
}

func (x *UploadSession) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *UploadSession) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

// CreateUploadSessionRequest carries the full session record to persist.
type CreateUploadSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       *UploadSession         `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUploadSessionRequest) Reset() {
	*x = CreateUploadSessionRequest{}
	mi := &file_database_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUploadSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUploadSessionRequest) ProtoMessage() {}

func (x *CreateUploadSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_database_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUploadSessionRequest.ProtoReflect.Descriptor instead.
func (*CreateUploadSessionRequest) Descriptor() ([]byte, []int) {
	return file_database_proto_rawDescGZIP(), []int{12}
}

func (x *CreateUploadSessionRequest) GetSession() *UploadSession {
	if x != nil {
		return x.Session
	}
	return nil
}

// GetUploadSessionRequest looks up a session by either its session_id or
// file_id — whichever non-empty field is provided is used as the lookup key.
type GetUploadSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	FileId        string                 `protobuf:"bytes,2,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUploadSessionRequest) Reset() {
	*x = GetUploadSessionRequest{}
	mi := &file_database_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUploadSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUploadSessionRequest) ProtoMessage() {}

func (x *GetUploadSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_database_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUploadSessionRequest.ProtoReflect.Descriptor instead.
func (*GetUploadSessionRequest) Descriptor() ([]byte, []int) {
	return file_database_proto_rawDescGZIP(), []int{13}
}

func (x *GetUploadSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *GetUploadSessionRequest) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

// GetUploadSessionResponse returns the found session or a NOT_FOUND status.
type GetUploadSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       *UploadSession         `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUploadSessionResponse) Reset() {
	*x = GetUploadSessionResponse{}
	mi := &file_database_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUploadSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUploadSessionResponse) ProtoMessage() {}

func (x *GetUploadSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_database_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUploadSessionResponse.ProtoReflect.Descriptor instead.
func (*GetUploadSessionResponse) Descriptor() ([]byte, []int) {
	return file_database_proto_rawDescGZIP(), []int{14}
}

func (x *GetUploadSessionResponse) GetSession() *UploadSession {
	if x != nil {
		return x.Session
	}
	return nil
}

// AddCompletedPartRequest records a successfully uploaded chunk for a session.
type AddCompletedPartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Part          *UploadSessionPart     `protobuf:"bytes,2,opt,name=part,proto3" json:"part,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddCompletedPartRequest) Reset() {
	*x = AddCompletedPartRequest{}
	mi := &file_database_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddCompletedPartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCompletedPartRequest) ProtoMessage() {}

func (x *AddCompletedPartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_database_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddCompletedPartRequest.ProtoReflect.Descriptor instead.
func (*AddCompletedPartRequest) Descriptor() ([]byte, []int) {
	return file_database_proto_rawDescGZIP(), []int{15}
}

func (x *AddCompletedPartRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *AddCompletedPartRequest) GetPart() *UploadSessionPart {
	if x != nil {
		return x.Part
	}
	return nil
}

// CompleteUploadSessionRequest marks the upload session as assembled and
// instructs the database service to clear the stored encryption key.
type CompleteUploadSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteUploadSessionRequest) Reset() {
	*x = CompleteUploadSessionRequest{}
	mi := &file_database_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteUploadSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteUploadSessionRequest) ProtoMessage() {}

func (x *CompleteUploadSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_database_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteUploadSessionRequest.ProtoReflect.Descriptor instead.
func (*CompleteUploadSessionRequest) Descriptor() ([]byte, []int) {
	return file_database_proto_rawDescGZIP(), []int{16}
}

func (x *CompleteUploadSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

// DeleteUploadSessionRequest removes a single upload session row.
type DeleteUploadSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUploadSessionRequest) Reset() {
	*x = DeleteUploadSessionRequest{}
	mi := &file_database_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUploadSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUploadSessionRequest) ProtoMessage() {}

func (x *DeleteUploadSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_database_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUploadSessionRequest.ProtoReflect.Descriptor instead.
func (*DeleteUploadSessionRequest) Descriptor() ([]byte, []int) {
	return file_database_proto_rawDescGZIP(), []int{17}
}

func (x *DeleteUploadSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

// DeleteExpiredUploadSessionsRequest triggers a sweep of all incomplete
// sessions whose expires_at is before as_of.
type DeleteExpiredUploadSessionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AsOf          string                 `protobuf:"bytes,1,opt,name=as_of,json=asOf,proto3" json:"as_of,omitempty"` // RFC3339 timestamp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteExpiredUploadSessionsRequest) Reset() {
	*x = DeleteExpiredUploadSessionsRequest{}
	mi := &file_database_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteExpiredUploadSessionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteExpiredUploadSessionsRequest) ProtoMessage() {}

func (x *DeleteExpiredUploadSessionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_database_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteExpiredUploadSessionsRequest.ProtoReflect.Descriptor instead.
func (*DeleteExpiredUploadSessionsRequest) Descriptor() ([]byte, []int) {
	return file_database_proto_rawDescGZIP(), []int{18}
}

func (x *DeleteExpiredUploadSessionsRequest) GetAsOf() string {
	if x != nil {
		return x.AsOf
	}
	return ""
}

// DeleteExpiredUploadSessionsResponse returns the sessions that were removed
// so the caller can release their associated multipart uploads in object
// storage.
type DeleteExpiredUploadSessionsResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RemovedSessions []*UploadSession       `protobuf:"bytes,1,rep,name=removed_sessions,json=removedSessions,proto3" json:"removed_sessions,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DeleteExpiredUploadSessionsResponse) Reset() {
	*x = DeleteExpiredUploadSessionsResponse{}
	mi := &file_database_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteExpiredUploadSessionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteExpiredUploadSessionsResponse) ProtoMessage() {}

func (x *DeleteExpiredUploadSessionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_database_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteExpiredUploadSessionsResponse.ProtoReflect.Descriptor instead.
func (*DeleteExpiredUploadSessionsResponse) Descriptor() ([]byte, []int) {
	return file_database_proto_rawDescGZIP(), []int{19}
}

func (x *DeleteExpiredUploadSessionsResponse) GetRemovedSessions() []*UploadSession {
	if x != nil {
		return x.RemovedSessions
	}
	return nil
}

var File_database_proto protoreflect.FileDescriptor

const file_database_proto_rawDesc = "" +
	"\n" +
	"\x0edatabase.proto\x12\n" +
	"databasepb\x1a\x1bgoogle/protobuf/empty.proto\"#\n" +
	"\rSelectRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\"\xf2\x01\n" +
	"\x0eSelectResponse\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x1e\n" +
	"\n" +
	"passphrase\x18\x03 \x01(\tR\n" +
	"passphrase\x12\x1d\n" +
	"\n" +
	"view_count\x18\x04 \x01(\x05R\tviewCount\x12$\n" +
	"\x0emax_view_count\x18\x05 \x01(\x05R\fmaxViewCount\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x06 \x01(\tR\texpiresAt\x12.\n" +
	"\x13is_client_encrypted\x18\a \x01(\bR\x11isClientEncrypted\"\xfb\x01\n" +
	"\rInsertRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x1e\n" +
	"\n" +
	"passphrase\x18\x03 \x01(\tR\n" +
	"passphrase\x12$\n" +
	"\x0emax_view_count\x18\x04 \x01(\x05R\fmaxViewCount\x12'\n" +
	"\x0frecipient_email\x18\x05 \x01(\tR\x0erecipientEmail\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x06 \x01(\tR\texpiresAt\x12.\n" +
	"\x13is_client_encrypted\x18\a \x01(\bR\x11isClientEncrypted\"\xa3\x01\n" +
	"\x1aGetUnviewedMessagesRequest\x12(\n" +
	"\x10older_than_hours\x18\x01 \x01(\x05R\x0eolderThanHours\x12#\n" +
	"\rmax_reminders\x18\x02 \x01(\x05R\fmaxReminders\x126\n" +
	"\x17reminder_interval_hours\x18\x03 \x01(\x05R\x15reminderIntervalHours\"\xab\x01\n" +
	"\x0fUnviewedMessage\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\x05R\tmessageId\x12\x1b\n" +
	"\tunique_id\x18\x02 \x01(\tR\buniqueId\x12'\n" +
	"\x0frecipient_email\x18\x03 \x01(\tR\x0erecipientEmail\x12\x18\n" +
	"\acreated\x18\x04 \x01(\tR\acreated\x12\x19\n" +
	"\bdays_old\x18\x05 \x01(\x05R\adaysOld\"V\n" +
	"\x1bGetUnviewedMessagesResponse\x127\n" +
	"\bmessages\x18\x01 \x03(\v2\x1b.databasepb.UnviewedMessageR\bmessages\"X\n" +
	"\x12LogReminderRequest\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\x05R\tmessageId\x12#\n" +
	"\remail_address\x18\x02 \x01(\tR\femailAddress\":\n" +
	"\x19GetReminderHistoryRequest\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\x05R\tmessageId\"\xab\x01\n" +
	"\x10ReminderLogEntry\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\x05R\tmessageId\x12#\n" +
	"\remail_address\x18\x02 \x01(\tR\femailAddress\x12%\n" +
	"\x0ereminder_count\x18\x03 \x01(\x05R\rreminderCount\x12,\n" +
	"\x12last_reminder_sent\x18\x04 \x01(\tR\x10lastReminderSent\"T\n" +
	"\x1aGetReminderHistoryResponse\x126\n" +
	"\aentries\x18\x01 \x03(\v2\x1c.databasepb.ReminderLogEntryR\aentries\"H\n" +
	"\x11UploadSessionPart\x12\x1f\n" +
	"\vpart_number\x18\x01 \x01(\x05R\n" +
	"partNumber\x12\x12\n" +
	"\x04etag\x18\x02 \x01(\tR\x04etag\"\xc9\x03\n" +
	"\rUploadSession\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x17\n" +
	"\afile_id\x18\x02 \x01(\tR\x06fileId\x12\x1d\n" +
	"\n" +
	"message_id\x18\x03 \x01(\tR\tmessageId\x12\x1b\n" +
	"\tupload_id\x18\x04 \x01(\tR\buploadId\x12\x1a\n" +
	"\bfilename\x18\x05 \x01(\tR\bfilename\x12!\n" +
	"\fcontent_type\x18\x06 \x01(\tR\vcontentType\x12\x1d\n" +
	"\n" +
	"total_size\x18\a \x01(\x03R\ttotalSize\x12!\n" +
	"\ftotal_chunks\x18\b \x01(\x05R\vtotalChunks\x12\x16\n" +
	"\x06status\x18\t \x01(\tR\x06status\x12%\n" +
	"\x0eencryption_key\x18\n" +
	" \x01(\fR\rencryptionKey\x12F\n" +
	"\x0fcompleted_parts\x18\v \x03(\v2\x1d.databasepb.UploadSessionPartR\x0ecompletedParts\x12\x1d\n" +
	"\n" +
	"created_at\x18\f \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"expires_at\x18\r \x01(\tR\texpiresAt\"Q\n" +
	"\x1aCreateUploadSessionRequest\x123\n" +
	"\asession\x18\x01 \x01(\v2\x19.databasepb.UploadSessionR\asession\"Q\n" +
	"\x17GetUploadSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x17\n" +
	"\afile_id\x18\x02 \x01(\tR\x06fileId\"O\n" +
	"\x18GetUploadSessionResponse\x123\n" +
	"\asession\x18\x01 \x01(\v2\x19.databasepb.UploadSessionR\asession\"k\n" +
	"\x17AddCompletedPartRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x121\n" +
	"\x04part\x18\x02 \x01(\v2\x1d.databasepb.UploadSessionPartR\x04part\"=\n" +
	"\x1cCompleteUploadSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\";\n" +
	"\x1aDeleteUploadSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"9\n" +
	"\"DeleteExpiredUploadSessionsRequest\x12\x13\n" +
	"\x05as_of\x18\x01 \x01(\tR\x04asOf\"k\n" +
	"#DeleteExpiredUploadSessionsResponse\x12D\n" +
	"\x10removed_sessions\x18\x01 \x03(\v2\x19.databasepb.UploadSessionR\x0fremovedSessions2\xc4\b\n" +
	"\tdbService\x12A\n" +
	"\x06Select\x12\x19.databasepb.SelectRequest\x1a\x1a.databasepb.SelectResponse\"\x00\x12=\n" +
	"\x06Insert\x12\x19.databasepb.InsertRequest\x1a\x16.google.protobuf.Empty\"\x00\x12E\n" +
	"\n" +
	"GetMessage\x12\x19.databasepb.SelectRequest\x1a\x1a.databasepb.SelectResponse\"\x00\x12t\n" +
	"\x1fGetUnviewedMessagesForReminders\x12&.databasepb.GetUnviewedMessagesRequest\x1a'.databasepb.GetUnviewedMessagesResponse\"\x00\x12K\n" +
	"\x0fLogReminderSent\x12\x1e.databasepb.LogReminderRequest\x1a\x16.google.protobuf.Empty\"\x00\x12e\n" +
	"\x12GetReminderHistory\x12%.databasepb.GetReminderHistoryRequest\x1a&.databasepb.GetReminderHistoryResponse\"\x00\x12W\n" +
	"\x13CreateUploadSession\x12&.databasepb.CreateUploadSessionRequest\x1a\x16.google.protobuf.Empty\"\x00\x12_\n" +
	"\x10GetUploadSession\x12#.databasepb.GetUploadSessionRequest\x1a$.databasepb.GetUploadSessionResponse\"\x00\x12Q\n" +
	"\x10AddCompletedPart\x12#.databasepb.AddCompletedPartRequest\x1a\x16.google.protobuf.Empty\"\x00\x12[\n" +
	"\x15CompleteUploadSession\x12(.databasepb.CompleteUploadSessionRequest\x1a\x16.google.protobuf.Empty\"\x00\x12W\n" +
	"\x13DeleteUploadSession\x12&.databasepb.DeleteUploadSessionRequest\x1a\x16.google.protobuf.Empty\"\x00\x12\x80\x01\n" +
	"\x1bDeleteExpiredUploadSessions\x12..databasepb.DeleteExpiredUploadSessionsRequest\x1a/.databasepb.DeleteExpiredUploadSessionsResponse\"\x00B;Z9github.com/Anthony-Bible/password-exchange/app/databasepbb\x06proto3"

var (
	file_database_proto_rawDescOnce sync.Once
	file_database_proto_rawDescData []byte
)

func file_database_proto_rawDescGZIP() []byte {
	file_database_proto_rawDescOnce.Do(func() {
		file_database_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_database_proto_rawDesc), len(file_database_proto_rawDesc)))
	})
	return file_database_proto_rawDescData
}

var file_database_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_database_proto_goTypes = []any{
	(*SelectRequest)(nil),                       // 0: databasepb.SelectRequest
	(*SelectResponse)(nil),                      // 1: databasepb.SelectResponse
	(*InsertRequest)(nil),                       // 2: databasepb.InsertRequest
	(*GetUnviewedMessagesRequest)(nil),          // 3: databasepb.GetUnviewedMessagesRequest
	(*UnviewedMessage)(nil),                     // 4: databasepb.UnviewedMessage
	(*GetUnviewedMessagesResponse)(nil),         // 5: databasepb.GetUnviewedMessagesResponse
	(*LogReminderRequest)(nil),                  // 6: databasepb.LogReminderRequest
	(*GetReminderHistoryRequest)(nil),           // 7: databasepb.GetReminderHistoryRequest
	(*ReminderLogEntry)(nil),                    // 8: databasepb.ReminderLogEntry
	(*GetReminderHistoryResponse)(nil),          // 9: databasepb.GetReminderHistoryResponse
	(*UploadSessionPart)(nil),                   // 10: databasepb.UploadSessionPart
	(*UploadSession)(nil),                       // 11: databasepb.UploadSession
	(*CreateUploadSessionRequest)(nil),          // 12: databasepb.CreateUploadSessionRequest
	(*GetUploadSessionRequest)(nil),             // 13: databasepb.GetUploadSessionRequest
	(*GetUploadSessionResponse)(nil),            // 14: databasepb.GetUploadSessionResponse
	(*AddCompletedPartRequest)(nil),             // 15: databasepb.AddCompletedPartRequest
	(*CompleteUploadSessionRequest)(nil),        // 16: databasepb.CompleteUploadSessionRequest
	(*DeleteUploadSessionRequest)(nil),          // 17: databasepb.DeleteUploadSessionRequest
	(*DeleteExpiredUploadSessionsRequest)(nil),  // 18: databasepb.DeleteExpiredUploadSessionsRequest
	(*DeleteExpiredUploadSessionsResponse)(nil), // 19: databasepb.DeleteExpiredUploadSessionsResponse
	(*emptypb.Empty)(nil),                       // 20: google.protobuf.Empty
}
var file_database_proto_depIdxs = []int32{
	4,  // 0: databasepb.GetUnviewedMessagesResponse.messages:type_name -> databasepb.UnviewedMessage
	8,  // 1: databasepb.GetReminderHistoryResponse.entries:type_name -> databasepb.ReminderLogEntry
	10, // 2: databasepb.UploadSession.completed_parts:type_name -> databasepb.UploadSessionPart
	11, // 3: databasepb.CreateUploadSessionRequest.session:type_name -> databasepb.UploadSession
	11, // 4: databasepb.GetUploadSessionResponse.session:type_name -> databasepb.UploadSession
	10, // 5: databasepb.AddCompletedPartRequest.part:type_name -> databasepb.UploadSessionPart
	11, // 6: databasepb.DeleteExpiredUploadSessionsResponse.removed_sessions:type_name -> databasepb.UploadSession
	0,  // 7: databasepb.dbService.Select:input_type -> databasepb.SelectRequest
	2,  // 8: databasepb.dbService.Insert:input_type -> databasepb.InsertRequest
	0,  // 9: databasepb.dbService.GetMessage:input_type -> databasepb.SelectRequest
	3,  // 10: databasepb.dbService.GetUnviewedMessagesForReminders:input_type -> databasepb.GetUnviewedMessagesRequest
	6,  // 11: databasepb.dbService.LogReminderSent:input_type -> databasepb.LogReminderRequest
	7,  // 12: databasepb.dbService.GetReminderHistory:input_type -> databasepb.GetReminderHistoryRequest
	12, // 13: databasepb.dbService.CreateUploadSession:input_type -> databasepb.CreateUploadSessionRequest
	13, // 14: databasepb.dbService.GetUploadSession:input_type -> databasepb.GetUploadSessionRequest
	15, // 15: databasepb.dbService.AddCompletedPart:input_type -> databasepb.AddCompletedPartRequest
	16, // 16: databasepb.dbService.CompleteUploadSession:input_type -> databasepb.CompleteUploadSessionRequest
	17, // 17: databasepb.dbService.DeleteUploadSession:input_type -> databasepb.DeleteUploadSessionRequest
	18, // 18: databasepb.dbService.DeleteExpiredUploadSessions:input_type -> databasepb.DeleteExpiredUploadSessionsRequest
	1,  // 19: databasepb.dbService.Select:output_type -> databasepb.SelectResponse
	20, // 20: databasepb.dbService.Insert:output_type -> google.protobuf.Empty
	1,  // 21: databasepb.dbService.GetMessage:output_type -> databasepb.SelectResponse
	5,  // 22: databasepb.dbService.GetUnviewedMessagesForReminders:output_type -> databasepb.GetUnviewedMessagesResponse
	20, // 23: databasepb.dbService.LogReminderSent:output_type -> google.protobuf.Empty
	9,  // 24: databasepb.dbService.GetReminderHistory:output_type -> databasepb.GetReminderHistoryResponse
	20, // 25: databasepb.dbService.CreateUploadSession:output_type -> google.protobuf.Empty
	14, // 26: databasepb.dbService.GetUploadSession:output_type -> databasepb.GetUploadSessionResponse
	20, // 27: databasepb.dbService.AddCompletedPart:output_type -> google.protobuf.Empty
	20, // 28: databasepb.dbService.CompleteUploadSession:output_type -> google.protobuf.Empty
	20, // 29: databasepb.dbService.DeleteUploadSession:output_type -> google.protobuf.Empty
	19, // 30: databasepb.dbService.DeleteExpiredUploadSessions:output_type -> databasepb.DeleteExpiredUploadSessionsResponse
	19, // [19:31] is the sub-list for method output_type
	7,  // [7:19] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_database_proto_init() }
func file_database_proto_init() {
	if File_database_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_database_proto_rawDesc), len(file_database_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_database_proto_goTypes,
		DependencyIndexes: file_database_proto_depIdxs,
		MessageInfos:      file_database_proto_msgTypes,
	}.Build()
	File_database_proto = out.File
	file_database_proto_goTypes = nil
	file_database_proto_depIdxs = nil
}
