apiVersion: v1
kind: Service
metadata:
  name: database-service 
  annotations:
    # external-dns.alpha.kubernetes.io/hostname: anthony.bible
  namespace: default
spec:
  selector:
    app: database 
  ports:
    - name: http
      port: 50051 
      targetPort: 50051

