apiVersion: v1
kind: Service
metadata:
  name: database-%{PHASE}-service 
  annotations:
  namespace: default
spec:
  selector:
    app: database
    phase: %{PHASE}
  ports:
    - name: grpc 
      port: 50051 
      targetPort: 50051

