apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: database
  name: database-deployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
        # Have to disable outbound ports since it's outside of cluster: https://linkerd.io/2.11/reference/proxy-configuration/
        config.linkerd.io/skip-outbound-ports: "3306"
      labels:
        app: database
        name: database
        phase: "%{PHASE}"
        version: "%{VERSION}" 
    spec:
      containers:
      - envFrom:
        - secretRef:
            name: test-secret
        image: ghcr.io/anthony-bible/passwordexchange-database
        name: database

