apiVersion: v1
kind: Service
metadata:
  name: database-dev-service 
  annotations:
  namespace: default
spec:
  selector:
    app: database 
    phase: DEV
  ports:
    - name: grpc 
      port: 50051 
      targetPort: 50051

