apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello
spec:
  schedule: "0 0  * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            traffic.sidecar.istio.io/excludeOutboundIPRanges: 0.0.0.0/0
            sidecar.istio.io/inject: “false”
          labels:
            cronjob: "deleteMessages"
        spec:
          containers:
          - name: delete-messages 
            image: mariadb 
            env:
              - name: DELETEMESSAGES_PASS
                valueFrom: 
                  secretKeyRef:
                   name: test-secret
                   key: DELETEMESSAGES_PASS
              - name: DELETEMESSAGES_USER
                valueFrom: 
                  secretKeyRef:
                   name: test-secret
                   key: DELETEMESSAGES_USER
              - name: PASSWORDEXCHANGE_DBHOST
                valueFrom: 
                  secretKeyRef:
                   name: test-secret
                   key: PASSWORDEXCHANGE_DBHOST
              - name: PASSWORDEXCHANGE_DBNAME
                valueFrom: 
                  secretKeyRef:
                   name: test-secret
                   key: PASSWORDEXCHANGE_DBNAME
            imagePullPolicy: IfNotPresent
            command:
             - /bin/bash 
             - -c
             - mysql -h $PASSWORDEXCHANGE_DBHOST -u $DELETEMESSAGES_USER -p$DELETEMESSAGES_PASS  -E -e "delete from messages where created < now() - interval 7 DAY;" $PASSWORDEXCHANGE_DBNAME
          restartPolicy: OnFailure
