apiVersion: batch/v1
kind: Job
metadata:
  name: e2e-tests-firefox-%{VERSION}
  namespace: default
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  backoffLimit: 0
  ttlSecondsAfterFinished: 3600
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: playwright
          image: ghcr.io/anthony-bible/passwordexchange-e2e-firefox-%{PHASE}:%{VERSION}
          env:
            - name: BASE_URL
              value: "%{BASE_URL}"
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "2Gi"
              cpu: "1000m"
