apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: email 
  name: email-%{PHASE}-deployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: email 
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
        proxy.istio.io/config: '{ "holdApplicationUntilProxyStarts": true }'
      labels:
        app: email 
        name: email 
        phase: "%{PHASE}"
        version: "%{VERSION}" 
    spec:
      containers:
      - envFrom:
        - secretRef:
            name: test-secret
        image: ghcr.io/anthony-bible/passwordexchange-container-prod
        args: ["email"]
        env:
        - name: "PASSWORDEXCHANGE_RUNNINGENVIRONMENT"
          value: "%{PHASE}"
        name: email
        ports:
        - containerPort: 8080




