apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: encryption
  name: encryption-%{PHASE}-deployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: encryption
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
        proxy.istio.io/config: '{ "holdApplicationUntilProxyStarts": true }'
      labels:
        app: encryption
        name: encryption
        phase: "%{PHASE}"
        version: "%{VERSION}" 
    spec:
      containers:
      - envFrom:
        - secretRef:
            name: test-secret
        image: ghcr.io/anthony-bible/passwordexchange-container-%{PHASE}@%{MAIN_IMAGE_SHA}
        args: ["encryption"]
        env:
        - name: "PASSWORDEXCHANGE_RUNNING_ENVIRONMENT"
          value: "%{PHASE}"
        name: encryption

---



