apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: encryption
  name: encryption-deployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: encryption
  template:
    metadata:
      annotations:
        iam.amazonaws.com/role: arn:aws:iam::842805395457:role/Test_ec2ForSDK
        linkerd.io/inject: enabled
      labels:
        app: encryption
        name: encryption
        phase: prod
    spec:
      containers:
      - envFrom:
        - secretRef:
            name: test-secret
        image: ghcr.io/anthony-bible/passwordexchange-encryption
        name: setup
        volumeMounts:
        - mountPath: /code
          name: html
        - mountPath: /nginx
          name: nginx-config
        - mountPath: /php
          name: php-config
      imagePullSecrets:
      - name: regcred
      volumes:
      - emptyDir: {}
        name: php-socket
      - emptyDir: {}
        name: html
      - emptyDir: {}
        name: nginx-config
      - emptyDir: {}
        name: php-config
---


