apiVersion: v1
kind: Service
metadata:
  name: encryption-service 
  annotations:
    # external-dns.alpha.kubernetes.io/hostname: anthony.bible
  namespace: default
spec:
  selector:
    app: encryption 
    phase: PROD
  ports:
    - name: grpc 
      port: 50051 
      targetPort: 50051

