apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: passwordexchange
  name: passwordexchange-%{PHASE}-deployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: passwordexchange
  template:
    metadata:
      annotations:
        dapr.io/app-id: passwordexchange-web
        dapr.io/enabled: "true"
        linkerd.io/inject: enabled
        proxy.istio.io/config: '{ "holdApplicationUntilProxyStarts": true }'
      labels:
        app: passwordexchange
        name: passwordexchange
        phase: '%{PHASE}'
        version: '%{VERSION}'
    spec:
      containers:
      - args:
        - web
        env:
        - name: PASSWORDEXCHANGE_RUNNINGENVIRONMENT
          value: '%{PHASE}'
        envFrom:
        - secretRef:
            name: test-secret
        image: ghcr.io/anthony-bible/passwordexchange-container-prod
        name: password-exchange
        ports:
        - containerPort: 8080
