apiVersion: v1
kind: Service
metadata:
  name: passwordexchange-%{PHASE}-service 
  annotations:
    # external-dns.alpha.kubernetes.io/hostname: anthony.bible
    # Prometheus monitoring annotations
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
    prometheus.io/path: "/metrics"
  namespace: default
spec:
  selector:
    app: passwordexchange 
    phase: %{PHASE}
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
    - name: metrics
      port: 8080
      targetPort: 8080
      protocol: TCP

