apiVersion: v1
kind: Service
metadata:
  name: passwordexchange-service 
  annotations:
    # external-dns.alpha.kubernetes.io/hostname: anthony.bible
  namespace: default
spec:
  selector:
    app: passwordexchange 
    phase: PROD
  ports:
    - name: http
      port: 80
      targetPort: 8080

