apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: passwordexchange
  name: passwordexchange-%{PHASE}-deployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: passwordexchange
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: passwordexchange
        name: passwordexchange
        phase: "%{PHASE}"
        version: "%{VERSION}" 
    spec:
      containers:
      - envFrom:
        - secretRef:
            name: test-secret
        image: ghcr.io/anthony-bible/passwordexchange-container-prod
        env:
        - name: "PASSWORDEXCHANGE_RUNNING_ENVIRONMENT"
          value: "%{PHASE}"
        name: password-exchange
        ports:
        - containerPort: 8080




