# Install RabbitMQ Cluster Operator
# kubectl apply -f "https://github.com/rabbitmq/cluster-operator/releases/latest/download/cluster-operator.yml"

# RabbitMQ Cluster Instance
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmq
  namespace: default
spec:
  replicas: 3
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        preference:
          matchExpressions:
          - key: stable
            operator: In
            values:
            - rabbit
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                - rabbitmq
          topologyKey: "kubernetes.io/hostname"
  tolerations:
  - key: stable
    operator: Equal
    value: rabbit
    effect: NoSchedule
  service:
    type: ClusterIP
  persistence:
    storageClassName: "standard-rwo"  # Use default storage class
    storage: 3Gi
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 1Gi
  rabbitmq:
    additionalConfig: |
      management.tcp.port = 15672
      management.tcp.ip = 0.0.0.0
      log.console.level = info
    envConfig: |
      RABBITMQ_DEFAULT_USER=guest
      RABBITMQ_DEFAULT_PASS=guest
