apiVersion: v1
kind: Service
metadata:
  name: slackbot-service 
  annotations:
    # external-dns.alpha.kubernetes.io/hostname: anthony.bible
  namespace: default
spec:
  selector:
    app: slackbot 
  ports:
    - name: http
      port: 80 
      targetPort: 3000

