apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: slackbot
  name: slackbot-deployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: slackbot
  template:
    metadata:
      annotations:
        iam.amazonaws.com/role: arn:aws:iam::842805395457:role/Test_ec2ForSDK
        linkerd.io/inject: enabled
        config.linkerd.io/skip-outbound-ports: "3306"
      labels:
        app: slackbot
        name: slackbot
        phase: "%{PHASE}"
        version: "%{VERSION}" 
    spec:
      containers:
      - image: ghcr.io/anthony-bible/passwordexchange-slackbot@sha256:%{SLACKBOT_IMAGE_DIGEST}
        ports:
        - containerPort: 3000
        env:
          - name: PASSWORDEXCHANGE_ENCRYPTIONSERVICE
            valueFrom:
              secretKeyRef:
                key: PASSWORDEXCHANGE_ENCRYPTIONPRODSERVICE
                name: test-secret
          - name: PASSWORDEXCHANGE_DATABASESERVICE
            valueFrom:
              secretKeyRef:
                key: PASSWORDEXCHANGE_DATABASEPRODSERVICE
                name: test-secret
          - name: PASSWORDEXCHANGE_HOST
            valueFrom:
              secretKeyRef:
                key: PASSWORDEXCHANGE_PRODHOST
                name: test-secret
          - name: PASSWORDEXCHANGE_DBHOST
            valueFrom:
              secretKeyRef:
                key: PASSWORDEXCHANGE_DBHOST
                name: test-secret
          - name: OAUTHDB_PASSWORD
            valueFrom:
              secretKeyRef:
                key: OAUTHDB_PASSWORD
                name: test-secret
          - name: OAUTHDB_USER
            valueFrom:
              secretKeyRef:
                key: OAUTHDB_USER
                name: test-secret
          - name: OAUTHDB_NAME
            valueFrom:
              secretKeyRef:
                key: OAUTHDB_NAME
                name: test-secret
          - name: SLACK_SIGNING_SECRET
            valueFrom:
              secretKeyRef:
                key: SLACK_SIGNING_SECRET
                name: test-secret    
          - name: SLACK_CLIENT_ID
            valueFrom:
              secretKeyRef:
                key: SLACK_CLIENT_ID
                name: test-secret  
          - name: SLACK_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                key: SLACK_CLIENT_SECRET
                name: test-secret        
        name: slackbot



