version: '3.3'
services:
    password-exchange:
        ports:
            - '80:8080'
        container_name: password_exchange
        volumes:
            - 'true'
        environment:
          - PASSWORDEXCHANGE_EMAILUSER=email_user
          - PASSWORDEXCHANGE_EMAILPASS=email_password
          - PASSWORDEXCHANGE_EMAILHOST=email-smtp.us-west-2.amazonaws.com
          - PASSWORDEXCHANGE_EMAILPORT=587
          - PASSWORDEXCHANGE_HOST=https://passwordexchange.com
          - PASSWORDEXCHANGE_DBNAME=passwordExchange
          - PASSWORDEXCHANGE_DBHOST=db.example.com
          - PASSWORDEXCHANGE_DBPASS=db_password
          - PASSWORDEXCHANGE_DBUSER=db_user
          - PASSWORDEXCHANGE_DBPORT=3306
          - PORT=8080

        restart: always
        image: 'ghcr.io/anthony-bible/passwordexchange-container-prod:0.0.7'
