---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: passwordexchange-deployment
  namespace: default
  labels:
    app: passwordexchange
spec:
  selector:
    matchLabels:
      app: passwordexchange
  replicas: 2
  template: 
    metadata:
      labels:
        app: passwordexchange 
        name: "passwordexchange"
        phase: "prod" 
      annotations:
        iam.amazonaws.com/role: arn:aws:iam::842805395457:role/Test_ec2ForSDK
    spec:
      containers:
      - name: setup
        image:  ghcr.io/anthony-bible/passwordexchange-container-prod@sha256:b95ed9b6714fae5653bda6afb8da367b862c1ce4e3b244c3838ad3cac71e86f5
        env:
          - name: PASSWORDEXCHANGE_EMAILUSER
            valueFrom: 
              secretKeyRef:
                name: test-secret
                key: PASSWORDEXCHANGE_EMAILUSER
          - name: PASSWORDEXCHANGE_EMAILPASS
            valueFrom: 
              secretKeyRef:
                name: test-secret
                key: PASSWORDEXCHANGE_EMAILPASS

          - name: PASSWORDEXCHANGE_DBPORT
            valueFrom: 
              secretKeyRef:
                name: test-secret
                key: PASSWORDEXCHANGE_DBPORT
          - name: PASSWORDEXCHANGE_DBNAME
            valueFrom: 
              secretKeyRef:
                name: test-secret
                key: PASSWORDEXCHANGE_DBNAME
          - name: PASSWORDEXCHANGE_DBPASS
            valueFrom: 
              secretKeyRef:
                name: test-secret
                key: PASSWORDEXCHANGE_DBPASS
          - name: PASSWORDEXCHANGE_DBUSER
            valueFrom: 
              secretKeyRef:
                name: test-secret
                key: PASSWORDEXCHANGE_DBUSER
          - name: PASSWORDEXCHANGE_DBHOST
            valueFrom: 
              secretKeyRef:
                name: test-secret
                key: PASSWORDEXCHANGE_DBHOST
          - name: PASSWORDEXCHANGE_EMAILHOST
            valueFrom: 
              secretKeyRef:
                name: test-secret
                key: PASSWORDEXCHANGE_EMAILHOST
          - name: PASSWORDEXCHANGE_HOST
            valueFrom: 
              secretKeyRef:
                name: test-secret
                key: PASSWORDEXCHANGE_HOST
          - name: PASSWORDEXCHANGE_EMAILPORT
            valueFrom: 
              secretKeyRef:
                name: test-secret
                key: PASSWORDEXCHANGE_EMAILPORT
        volumeMounts:
        - name: html
          mountPath: /code
        - name: nginx-config
          mountPath: /nginx 
        - name: php-config 
          mountPath: /php
      imagePullSecrets:
      - name: regcred
      volumes:
      - name: php-socket
        emptyDir: {}
      - name: html
        emptyDir: {}        
      - name: nginx-config
        emptyDir: {}        
      - name: php-config 
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: passwordexchange-service 
  annotations:
    # external-dns.alpha.kubernetes.io/hostname: anthony.bible
  namespace: default
spec:
  selector:
    app: passwordexchange 
  ports:
    - name: http
      port: 80
      targetPort: 8080
      
---
