---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: passwordexchange-deployment
  namespace: default
  labels:
    app: passwordexchange
spec:
  selector:
    matchLabels:
      app: passwordexchange
  replicas: 2
  template: 
    metadata:
      labels:
        app: passwordexchange 
        name: "passwordexchange"
        phase: "prod" 
      annotations:
        iam.amazonaws.com/role: arn:aws:iam::842805395457:role/Test_ec2ForSDK
    spec:
      containers:
      - name: site-fpm
        image: gimpyb/myphp-container:0.0.7
        resources:
          requests:
            memory: "64Mi"
            cpu: "10m"
        volumeMounts:
        - name: php-socket
          mountPath: /sock
        - name: html
          mountPath: "/var/www/html"
        - name: php-config 
          mountPath: "/usr/local/etc/php-fpm.d" 
      - name: nginx
        image: nginx:1.21.0-alpine
        resources:
          requests:
            memory: "64Mi"
            cpu: "10m"
        ports:
        - containerPort: 80
        volumeMounts:
        - name: php-socket
          mountPath: /sock
        - name: html
          mountPath: /var/www/html
        - name: nginx-config
          mountPath: /etc/nginx
      - name: setup
        image:  ghcr.io/anthony-bible/passwordexchange-container-prod@sha256:43b51bea548badd91092af4e56b74ac8893e5ef103d6712164f81840e2c65ce7
        env:
          - name: PASSWORDEXCHANGE_EMAILUSER
            valueFrom: 
              secretKeyRef:
                name: test-secret
                key: PASSWORDEXCHANGE_EMAILUSER
          - name: PASSWORDEXCHANGE_EMAILPASS
            valueFrom: 
              secretKeyRef:
                name: test-secret
                key: PASSWORDEXCHANGE_EMAILPASS
              
        volumeMounts:
        - name: html
          mountPath: /code
        - name: nginx-config
          mountPath: /nginx 
        - name: php-config 
          mountPath: /php
      imagePullSecrets:
      - name: regcred
      volumes:
      - name: php-socket
        emptyDir: {}
      - name: html
        emptyDir: {}        
      - name: nginx-config
        emptyDir: {}        
      - name: php-config 
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: passwordexchange-service 
  annotations:
    # external-dns.alpha.kubernetes.io/hostname: anthony.bible
  namespace: default
spec:
  selector:
    app: passwordexchange 
  ports:
    - name: http2
      port: 80
      targetPort: 80  
      
---
