// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: encryption.proto

package encryptionpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EncryptedMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlainText     []string               `protobuf:"bytes,1,rep,name=PlainText,proto3" json:"PlainText,omitempty"`
	Key           []byte                 `protobuf:"bytes,2,opt,name=Key,proto3" json:"Key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EncryptedMessageRequest) Reset() {
	*x = EncryptedMessageRequest{}
	mi := &file_encryption_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EncryptedMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncryptedMessageRequest) ProtoMessage() {}

func (x *EncryptedMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_encryption_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncryptedMessageRequest.ProtoReflect.Descriptor instead.
func (*EncryptedMessageRequest) Descriptor() ([]byte, []int) {
	return file_encryption_proto_rawDescGZIP(), []int{0}
}

func (x *EncryptedMessageRequest) GetPlainText() []string {
	if x != nil {
		return x.PlainText
	}
	return nil
}

func (x *EncryptedMessageRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

type EncryptedMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ciphertext    []string               `protobuf:"bytes,1,rep,name=Ciphertext,proto3" json:"Ciphertext,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EncryptedMessageResponse) Reset() {
	*x = EncryptedMessageResponse{}
	mi := &file_encryption_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EncryptedMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncryptedMessageResponse) ProtoMessage() {}

func (x *EncryptedMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_encryption_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncryptedMessageResponse.ProtoReflect.Descriptor instead.
func (*EncryptedMessageResponse) Descriptor() ([]byte, []int) {
	return file_encryption_proto_rawDescGZIP(), []int{1}
}

func (x *EncryptedMessageResponse) GetCiphertext() []string {
	if x != nil {
		return x.Ciphertext
	}
	return nil
}

type DecryptedMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ciphertext    []string               `protobuf:"bytes,1,rep,name=Ciphertext,proto3" json:"Ciphertext,omitempty"`
	Key           []byte                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecryptedMessageRequest) Reset() {
	*x = DecryptedMessageRequest{}
	mi := &file_encryption_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecryptedMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecryptedMessageRequest) ProtoMessage() {}

func (x *DecryptedMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_encryption_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecryptedMessageRequest.ProtoReflect.Descriptor instead.
func (*DecryptedMessageRequest) Descriptor() ([]byte, []int) {
	return file_encryption_proto_rawDescGZIP(), []int{2}
}

func (x *DecryptedMessageRequest) GetCiphertext() []string {
	if x != nil {
		return x.Ciphertext
	}
	return nil
}

func (x *DecryptedMessageRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

type DecryptedMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Plaintext     []string               `protobuf:"bytes,1,rep,name=plaintext,proto3" json:"plaintext,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecryptedMessageResponse) Reset() {
	*x = DecryptedMessageResponse{}
	mi := &file_encryption_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecryptedMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecryptedMessageResponse) ProtoMessage() {}

func (x *DecryptedMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_encryption_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecryptedMessageResponse.ProtoReflect.Descriptor instead.
func (*DecryptedMessageResponse) Descriptor() ([]byte, []int) {
	return file_encryption_proto_rawDescGZIP(), []int{3}
}

func (x *DecryptedMessageResponse) GetPlaintext() []string {
	if x != nil {
		return x.Plaintext
	}
	return nil
}

type Randomresponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Encryptionbytes  []byte                 `protobuf:"bytes,1,opt,name=encryptionbytes,proto3" json:"encryptionbytes,omitempty"`
	EncryptionString string                 `protobuf:"bytes,2,opt,name=encryptionString,proto3" json:"encryptionString,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Randomresponse) Reset() {
	*x = Randomresponse{}
	mi := &file_encryption_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Randomresponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Randomresponse) ProtoMessage() {}

func (x *Randomresponse) ProtoReflect() protoreflect.Message {
	mi := &file_encryption_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Randomresponse.ProtoReflect.Descriptor instead.
func (*Randomresponse) Descriptor() ([]byte, []int) {
	return file_encryption_proto_rawDescGZIP(), []int{4}
}

func (x *Randomresponse) GetEncryptionbytes() []byte {
	if x != nil {
		return x.Encryptionbytes
	}
	return nil
}

func (x *Randomresponse) GetEncryptionString() string {
	if x != nil {
		return x.EncryptionString
	}
	return ""
}

type Randomrequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RandomLength  int32                  `protobuf:"varint,1,opt,name=randomLength,proto3" json:"randomLength,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Randomrequest) Reset() {
	*x = Randomrequest{}
	mi := &file_encryption_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Randomrequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Randomrequest) ProtoMessage() {}

func (x *Randomrequest) ProtoReflect() protoreflect.Message {
	mi := &file_encryption_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Randomrequest.ProtoReflect.Descriptor instead.
func (*Randomrequest) Descriptor() ([]byte, []int) {
	return file_encryption_proto_rawDescGZIP(), []int{5}
}

func (x *Randomrequest) GetRandomLength() int32 {
	if x != nil {
		return x.RandomLength
	}
	return 0
}

var File_encryption_proto protoreflect.FileDescriptor

const file_encryption_proto_rawDesc = "" +
	"\n" +
	"\x10encryption.proto\x12\fencryptionpb\"I\n" +
	"\x17EncryptedMessageRequest\x12\x1c\n" +
	"\tPlainText\x18\x01 \x03(\tR\tPlainText\x12\x10\n" +
	"\x03Key\x18\x02 \x01(\fR\x03Key\":\n" +
	"\x18EncryptedMessageResponse\x12\x1e\n" +
	"\n" +
	"Ciphertext\x18\x01 \x03(\tR\n" +
	"Ciphertext\"K\n" +
	"\x17DecryptedMessageRequest\x12\x1e\n" +
	"\n" +
	"Ciphertext\x18\x01 \x03(\tR\n" +
	"Ciphertext\x12\x10\n" +
	"\x03key\x18\x02 \x01(\fR\x03key\"8\n" +
	"\x18DecryptedMessageResponse\x12\x1c\n" +
	"\tplaintext\x18\x01 \x03(\tR\tplaintext\"f\n" +
	"\x0eRandomresponse\x12(\n" +
	"\x0fencryptionbytes\x18\x01 \x01(\fR\x0fencryptionbytes\x12*\n" +
	"\x10encryptionString\x18\x02 \x01(\tR\x10encryptionString\"3\n" +
	"\rRandomrequest\x12\"\n" +
	"\frandomLength\x18\x01 \x01(\x05R\frandomLength2\xab\x02\n" +
	"\x0emessageService\x12a\n" +
	"\x0eencryptMessage\x12%.encryptionpb.EncryptedMessageRequest\x1a&.encryptionpb.EncryptedMessageResponse\"\x00\x12a\n" +
	"\x0eDecryptMessage\x12%.encryptionpb.DecryptedMessageRequest\x1a&.encryptionpb.DecryptedMessageResponse\"\x00\x12S\n" +
	"\x14GenerateRandomString\x12\x1b.encryptionpb.Randomrequest\x1a\x1c.encryptionpb.Randomresponse\"\x00B=Z;github.com/Anthony-Bible/password-exchange/app/encryptionpbb\x06proto3"

var (
	file_encryption_proto_rawDescOnce sync.Once
	file_encryption_proto_rawDescData []byte
)

func file_encryption_proto_rawDescGZIP() []byte {
	file_encryption_proto_rawDescOnce.Do(func() {
		file_encryption_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_encryption_proto_rawDesc), len(file_encryption_proto_rawDesc)))
	})
	return file_encryption_proto_rawDescData
}

var file_encryption_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_encryption_proto_goTypes = []any{
	(*EncryptedMessageRequest)(nil),  // 0: encryptionpb.EncryptedMessageRequest
	(*EncryptedMessageResponse)(nil), // 1: encryptionpb.EncryptedMessageResponse
	(*DecryptedMessageRequest)(nil),  // 2: encryptionpb.DecryptedMessageRequest
	(*DecryptedMessageResponse)(nil), // 3: encryptionpb.DecryptedMessageResponse
	(*Randomresponse)(nil),           // 4: encryptionpb.Randomresponse
	(*Randomrequest)(nil),            // 5: encryptionpb.Randomrequest
}
var file_encryption_proto_depIdxs = []int32{
	0, // 0: encryptionpb.messageService.encryptMessage:input_type -> encryptionpb.EncryptedMessageRequest
	2, // 1: encryptionpb.messageService.DecryptMessage:input_type -> encryptionpb.DecryptedMessageRequest
	5, // 2: encryptionpb.messageService.GenerateRandomString:input_type -> encryptionpb.Randomrequest
	1, // 3: encryptionpb.messageService.encryptMessage:output_type -> encryptionpb.EncryptedMessageResponse
	3, // 4: encryptionpb.messageService.DecryptMessage:output_type -> encryptionpb.DecryptedMessageResponse
	4, // 5: encryptionpb.messageService.GenerateRandomString:output_type -> encryptionpb.Randomresponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_encryption_proto_init() }
func file_encryption_proto_init() {
	if File_encryption_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_encryption_proto_rawDesc), len(file_encryption_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_encryption_proto_goTypes,
		DependencyIndexes: file_encryption_proto_depIdxs,
		MessageInfos:      file_encryption_proto_msgTypes,
	}.Build()
	File_encryption_proto = out.File
	file_encryption_proto_goTypes = nil
	file_encryption_proto_depIdxs = nil
}
