// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: encryption.proto

package encryptionpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MessageServiceClient is the client API for MessageService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MessageServiceClient interface {
	EncryptMessage(ctx context.Context, in *EncryptedMessageRequest, opts ...grpc.CallOption) (*EncryptedMessageResponse, error)
	DecryptMessage(ctx context.Context, in *DecryptedMessageRequest, opts ...grpc.CallOption) (*DecryptedMessageResponse, error)
	GenerateRandomString(ctx context.Context, in *Randomrequest, opts ...grpc.CallOption) (*Randomresponse, error)
}

type messageServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMessageServiceClient(cc grpc.ClientConnInterface) MessageServiceClient {
	return &messageServiceClient{cc}
}

func (c *messageServiceClient) EncryptMessage(ctx context.Context, in *EncryptedMessageRequest, opts ...grpc.CallOption) (*EncryptedMessageResponse, error) {
	out := new(EncryptedMessageResponse)
	err := c.cc.Invoke(ctx, "/encryptionpb.MessageService/encryptMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageServiceClient) DecryptMessage(ctx context.Context, in *DecryptedMessageRequest, opts ...grpc.CallOption) (*DecryptedMessageResponse, error) {
	out := new(DecryptedMessageResponse)
	err := c.cc.Invoke(ctx, "/encryptionpb.MessageService/DecryptMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageServiceClient) GenerateRandomString(ctx context.Context, in *Randomrequest, opts ...grpc.CallOption) (*Randomresponse, error) {
	out := new(Randomresponse)
	err := c.cc.Invoke(ctx, "/encryptionpb.MessageService/GenerateRandomString", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MessageServiceServer is the server API for MessageService service.
// All implementations must embed UnimplementedMessageServiceServer
// for forward compatibility
type MessageServiceServer interface {
	EncryptMessage(context.Context, *EncryptedMessageRequest) (*EncryptedMessageResponse, error)
	DecryptMessage(context.Context, *DecryptedMessageRequest) (*DecryptedMessageResponse, error)
	GenerateRandomString(context.Context, *Randomrequest) (*Randomresponse, error)
	mustEmbedUnimplementedMessageServiceServer()
}

// UnimplementedMessageServiceServer must be embedded to have forward compatible implementations.
type UnimplementedMessageServiceServer struct {
}

func (UnimplementedMessageServiceServer) EncryptMessage(context.Context, *EncryptedMessageRequest) (*EncryptedMessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EncryptMessage not implemented")
}
func (UnimplementedMessageServiceServer) DecryptMessage(context.Context, *DecryptedMessageRequest) (*DecryptedMessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DecryptMessage not implemented")
}
func (UnimplementedMessageServiceServer) GenerateRandomString(context.Context, *Randomrequest) (*Randomresponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateRandomString not implemented")
}
func (UnimplementedMessageServiceServer) mustEmbedUnimplementedMessageServiceServer() {}

// UnsafeMessageServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MessageServiceServer will
// result in compilation errors.
type UnsafeMessageServiceServer interface {
	mustEmbedUnimplementedMessageServiceServer()
}

func RegisterMessageServiceServer(s grpc.ServiceRegistrar, srv MessageServiceServer) {
	s.RegisterService(&MessageService_ServiceDesc, srv)
}

func _MessageService_EncryptMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EncryptedMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServiceServer).EncryptMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/encryptionpb.MessageService/encryptMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServiceServer).EncryptMessage(ctx, req.(*EncryptedMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageService_DecryptMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DecryptedMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServiceServer).DecryptMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/encryptionpb.MessageService/DecryptMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServiceServer).DecryptMessage(ctx, req.(*DecryptedMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageService_GenerateRandomString_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Randomrequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServiceServer).GenerateRandomString(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/encryptionpb.MessageService/GenerateRandomString",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServiceServer).GenerateRandomString(ctx, req.(*Randomrequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MessageService_ServiceDesc is the grpc.ServiceDesc for MessageService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MessageService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "encryptionpb.MessageService",
	HandlerType: (*MessageServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "encryptMessage",
			Handler:    _MessageService_EncryptMessage_Handler,
		},
		{
			MethodName: "DecryptMessage",
			Handler:    _MessageService_DecryptMessage_Handler,
		},
		{
			MethodName: "GenerateRandomString",
			Handler:    _MessageService_GenerateRandomString_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "encryption.proto",
}
