// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: message.proto

package messagepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Message struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Email          string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	FirstName      string                 `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	OtherFirstName string                 `protobuf:"bytes,3,opt,name=other_first_name,json=otherFirstName,proto3" json:"other_first_name,omitempty"`
	OtherLastName  string                 `protobuf:"bytes,4,opt,name=other_last_name,json=otherLastName,proto3" json:"other_last_name,omitempty"`
	OtherEmail     string                 `protobuf:"bytes,5,opt,name=other_email,json=otherEmail,proto3" json:"other_email,omitempty"`
	UniqueId       string                 `protobuf:"bytes,6,opt,name=unique_id,json=uniqueId,proto3" json:"unique_id,omitempty"`
	Content        string                 `protobuf:"bytes,7,opt,name=content,proto3" json:"content,omitempty"`
	Errors         string                 `protobuf:"bytes,8,opt,name=errors,proto3" json:"errors,omitempty"`
	Url            string                 `protobuf:"bytes,9,opt,name=url,proto3" json:"url,omitempty"`
	Hidden         string                 `protobuf:"bytes,10,opt,name=hidden,proto3" json:"hidden,omitempty"`
	Captcha        string                 `protobuf:"bytes,11,opt,name=captcha,proto3" json:"captcha,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Message) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *Message) GetOtherFirstName() string {
	if x != nil {
		return x.OtherFirstName
	}
	return ""
}

func (x *Message) GetOtherLastName() string {
	if x != nil {
		return x.OtherLastName
	}
	return ""
}

func (x *Message) GetOtherEmail() string {
	if x != nil {
		return x.OtherEmail
	}
	return ""
}

func (x *Message) GetUniqueId() string {
	if x != nil {
		return x.UniqueId
	}
	return ""
}

func (x *Message) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Message) GetErrors() string {
	if x != nil {
		return x.Errors
	}
	return ""
}

func (x *Message) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Message) GetHidden() string {
	if x != nil {
		return x.Hidden
	}
	return ""
}

func (x *Message) GetCaptcha() string {
	if x != nil {
		return x.Captcha
	}
	return ""
}

var File_message_proto protoreflect.FileDescriptor

const file_message_proto_rawDesc = "" +
	"\n" +
	"\rmessage.proto\x12\tmessagepb\"\xc4\x02\n" +
	"\aMessage\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1d\n" +
	"\n" +
	"first_name\x18\x02 \x01(\tR\tfirstName\x12(\n" +
	"\x10other_first_name\x18\x03 \x01(\tR\x0eotherFirstName\x12&\n" +
	"\x0fother_last_name\x18\x04 \x01(\tR\rotherLastName\x12\x1f\n" +
	"\vother_email\x18\x05 \x01(\tR\n" +
	"otherEmail\x12\x1b\n" +
	"\tunique_id\x18\x06 \x01(\tR\buniqueId\x12\x18\n" +
	"\acontent\x18\a \x01(\tR\acontent\x12\x16\n" +
	"\x06errors\x18\b \x01(\tR\x06errors\x12\x10\n" +
	"\x03url\x18\t \x01(\tR\x03url\x12\x16\n" +
	"\x06hidden\x18\n" +
	" \x01(\tR\x06hidden\x12\x18\n" +
	"\acaptcha\x18\v \x01(\tR\acaptchaB:Z8github.com/Anthony-Bible/password-exchange/app/messagepbb\x06proto3"

var (
	file_message_proto_rawDescOnce sync.Once
	file_message_proto_rawDescData []byte
)

func file_message_proto_rawDescGZIP() []byte {
	file_message_proto_rawDescOnce.Do(func() {
		file_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_message_proto_rawDesc), len(file_message_proto_rawDesc)))
	})
	return file_message_proto_rawDescData
}

var file_message_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_message_proto_goTypes = []any{
	(*Message)(nil), // 0: messagepb.Message
}
var file_message_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_message_proto_init() }
func file_message_proto_init() {
	if File_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_message_proto_rawDesc), len(file_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_message_proto_goTypes,
		DependencyIndexes: file_message_proto_depIdxs,
		MessageInfos:      file_message_proto_msgTypes,
	}.Build()
	File_message_proto = out.File
	file_message_proto_goTypes = nil
	file_message_proto_depIdxs = nil
}
