name: CI

on: [push, pull_request]

jobs:
  test:
    # virtual environments: https://github.com/actions/virtual-environments
    runs-on: ubuntu-20.04

    steps:
      # Caches and restores the bazelisk download directory.
      - name: Cache bazelisk download
        uses: actions/cache@v3
        env:
          cache-name: bazel-cache
        with:
          path: |
            ~/.cache/bazelisk
            ~/.cache/bazel     
          key: ${{ runner.os }}-${{ env.cache-name }}
          restore-keys: |
            ${{ runner.os }}-${{ env.cache-name }}-development
     

      # Checks-out your repository under $GITHUB_WORKSPACE, which is the CWD for
      # the rest of the steps

      - uses: actions/checkout@v3
      #install neccessary tools under $GITHUB_WORKSPACE
      - name: Install tools
        run: sudo apt update && sudo apt install -y libmariadb-dev
      - name: Install Skaffold
        run: |
          curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/v1.38.0/skaffold-linux-amd64 && \
          sudo install skaffold /usr/local/bin/
          skaffold version

      # build
      - name: get bazel version
        run: bazel version
      # - name: Build the code
      #   run: bazel build //... 
      - name: skaffold Build
        run: |
          echo "Building with skaffold"
          skaffold build ... --file-output=./images.json
      - name: skaffold rendering
        run: | 
          echo "rendering k8s manifests"
          skaffold render --file-output=/build/password-exchange.yaml


