name: CI

on: [push, pull_request]

jobs:
  test:
    # virtual environments: https://github.com/actions/virtual-environments
    runs-on: ubuntu-20.04

    steps:
      # Caches and restores the bazelisk download directory.
      - name: Cache bazelisk download
        uses: actions/cache@v3
        env:
          cache-name: bazel-cache
        with:
          path: |
            ~/.cache/bazelisk
            ~/.cache/bazel     
          key: ${{ runner.os }}-${{ env.cache-name }}
         
      # Checks-out your repository under $GITHUB_WORKSPACE, which is the CWD for
      # the rest of the steps
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PAT }}
      - uses: actions/checkout@v3
      #install neccessary tools under $GITHUB_WORKSPACE
      - name: Install tools
        run: sudo apt update && sudo apt install -y libmariadb-dev &&  sudo apt purge -y python2.7*

      - name: generate bazelrc
        env:
          BAZEL_USER: ${{ secrets.bazel_user }}
          BAZEL_PASS: ${{ secrets.bazel_pass }}
        run: |
          /bin/bash -c 'echo "run --stamp --workspace_status_command=./tools/bazel_stamp_vars.sh --remote_cache=https://$BAZEL_USER:$BAZEL_PASS@cache.anthony.bible" >> .bazelrc'
          /bin/bash -c 'echo "build --stamp --workspace_status_command=./tools/bazel_stamp_vars.sh --remote_cache=https://$BAZEL_USER:$BAZEL_PASS@cache.anthony.bible" >> .bazelrc'
      # build
      - name: get bazel version
        run: |
          bazel version
          python --version
          python3.8 -m venv .venv
          source .venv/bin/activate  # this in theory shouldn't be needed
      - name: Build the code
        run: bazel build //... 
      - name: Render manifests
        if: startsWith(github.ref, 'refs/tags/')
        run: | 
          mkdir build
          echo "rendering k8s manifests"
          bazel run //k8s:deployments-and-services --stamp --workspace_status_command=./tools/bazel_stamp_vars.sh  > ./build/password-exchange.yaml 
          
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ./build/password-exchange.yaml

